import {
    defineFieldRules,
    defineLocalFieldExclusions,
    type FieldDirection,
    type FieldRuleAnnotation,
} from "./conformance-fields-registry.js"

const discoveryEvidence = ["tests/discovery.test.ts"] as const
const memberEvidence = ["tests/member-search.test.ts"] as const
const memberIterationEvidence = ["tests/member-search-pagination.test.ts"] as const
const messageEvidence = ["tests/message-search.test.ts", "tests/conformance-fields-rules-search.test.ts"] as const
const messageIterationEvidence = ["tests/message-search-pagination.test.ts"] as const

const omitted = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "omitted", detail })
const noDefault = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "none", detail })
const providerDefault = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "provider", detail })
const valueDefault = (value: string, detail: string): FieldRuleAnnotation["default"] => ({
    kind: "value",
    value,
    detail,
})
const notApplicable = (detail: string): FieldRuleAnnotation["length"] => ({
    kind: "not-applicable",
    detail,
})
const bounded = (
    unit: Extract<FieldRuleAnnotation["length"], { kind: "bounded" }>["unit"],
    minimum: number | undefined,
    maximum: number | undefined,
    detail: string,
): FieldRuleAnnotation["length"] => ({
    kind: "bounded",
    unit,
    ...(minimum === undefined ? {} : { minimum }),
    ...(maximum === undefined ? {} : { maximum }),
    detail,
})
const preserved = (detail: string): FieldRuleAnnotation["normalization"] => ({ kind: "preserved", detail })
const canonicalized = (detail: string): FieldRuleAnnotation["normalization"] => ({
    kind: "canonicalized",
    detail,
})
const providerView = (detail: string): FieldRuleAnnotation["normalization"] => ({
    kind: "provider-normalized-view",
    detail,
})

function rules(
    targets: readonly string[],
    direction: FieldDirection,
    providerOwner: FieldRuleAnnotation["providerOwner"],
    sdkOwner: FieldRuleAnnotation["sdkOwner"],
    defaultRule: FieldRuleAnnotation["default"],
    length: FieldRuleAnnotation["length"],
    normalization: FieldRuleAnnotation["normalization"],
    executableEvidence: FieldRuleAnnotation["executableEvidence"],
): readonly FieldRuleAnnotation[] {
    return targets.map((target) => ({
        target,
        direction,
        providerOwner,
        sdkOwner,
        default: defaultRule,
        length,
        normalization,
        executableEvidence,
    }))
}

const optionalRequest = omitted("An absent optional public property is not serialized")
const requiredRequest = noDefault(
    "The apply request requires this field and neither the SDK nor Fluxer supplies a default",
)
const responseValue = noDefault("A valid provider response must supply this field; the SDK does not invent a value")
const scalar = notApplicable("This scalar has a value or format constraint rather than a length unit")
const unboundedResponse = notApplicable(
    "The pinned provider response schema and SDK projector publish no field-specific response-length bound",
)
const requestValue = preserved("The SDK validates the value and serializes it unchanged under the provider wire key")
const requestArray = preserved(
    "The SDK snapshots indexed entries and preserves their values and order in the wire array",
)
const responseProjection = providerView(
    "The SDK validates the provider value, projects its public key, and freezes the containing observation",
)

const discoverySchema = "packages/schema/src/domains/guild/GuildDiscoverySchemas.ts" as const
const discoverySdk = "src/internal/guild-discovery.ts" as const
const memberSchema = "packages/schema/src/domains/guild/GuildMemberSearchSchemas.ts" as const
const memberSdk = "src/internal/member-search.ts" as const
const messageRequestSchema = "packages/schema/src/domains/message/MessageRequestSchemas.ts" as const
const messageResponseSchema = "packages/schema/src/domains/message/MessageResponseSchemas.ts" as const
const messageSdk = "src/internal/message-search.ts" as const

const discoveryRequestRules = [
    ...rules(
        ["DiscoveryApplicationInput.description"],
        "request",
        `${discoverySchema}:DiscoveryApplicationRequest`,
        `${discoverySdk}:body`,
        requiredRequest,
        bounded("UTF-16-code-units", 10, 300, "The SDK and pinned schema enforce this inclusive raw string bound"),
        requestValue,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryApplicationInput.categoryId"],
        "request",
        `${discoverySchema}:DiscoveryApplicationRequest`,
        `${discoverySdk}:body`,
        requiredRequest,
        notApplicable("This integer category selector is restricted to 0 through 8, not measured by length"),
        requestValue,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryApplicationInput.primaryLanguage"],
        "request",
        `${discoverySchema}:DiscoveryApplicationRequest`,
        `${discoverySdk}:body`,
        providerDefault("Omission uses Fluxer's application default on apply and leaves the value unchanged on edit"),
        bounded(
            "UTF-16-code-units",
            2,
            35,
            "The SDK bounds the supported BCP-47-style language tag before provider validation",
        ),
        requestValue,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryApplicationInput.tags"],
        "request",
        `${discoverySchema}:DiscoveryApplicationRequest.DiscoveryTagsSchema`,
        `${discoverySdk}:body`,
        providerDefault("Omission produces an empty tag list on apply and leaves the list unchanged on edit"),
        bounded(
            "items",
            0,
            10,
            "At most ten tags are accepted; every raw and normalized tag must contain 2 through 30 UTF-16 code units",
        ),
        canonicalized("Each tag is trimmed, lowercased, whitespace-collapsed, and deduplicated in first-seen order"),
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchQuery.query"],
        "request",
        `${discoverySchema}:DiscoverySearchQuery`,
        `${discoverySdk}:discoverySearch`,
        optionalRequest,
        bounded("UTF-16-code-units", 0, 100, "The raw query may be empty and is capped at 100 code units"),
        requestValue,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchQuery.categoryId"],
        "request",
        `${discoverySchema}:DiscoverySearchQuery`,
        `${discoverySdk}:discoverySearch`,
        optionalRequest,
        notApplicable("This integer category filter is restricted to 0 through 8, not measured by length"),
        requestValue,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchQuery.primaryLanguage"],
        "request",
        `${discoverySchema}:DiscoverySearchQuery`,
        `${discoverySdk}:discoverySearch`,
        optionalRequest,
        bounded("UTF-16-code-units", 2, 35, "The SDK bounds and format-checks the language tag"),
        requestValue,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchQuery.tag"],
        "request",
        `${discoverySchema}:DiscoverySearchQuery`,
        `${discoverySdk}:discoverySearch`,
        optionalRequest,
        bounded("UTF-16-code-units", 0, 30, "The raw tag filter may be empty and is capped at 30 code units"),
        requestValue,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchQuery.sortBy"],
        "request",
        `${discoverySchema}:DiscoverySearchQuery`,
        `${discoverySdk}:discoverySearch`,
        providerDefault("Omission leaves ordering to Fluxer's directory-search default"),
        scalar,
        canonicalized("The public memberCount and onlineCount literals become member_count and online_count"),
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchQuery.limit"],
        "request",
        `${discoverySchema}:DiscoverySearchQuery`,
        `${discoverySdk}:discoverySearch`,
        valueDefault("24", "The SDK always serializes the provider's default page capacity of 24"),
        bounded("items", 1, 48, "The requested result capacity is an integer in this inclusive range"),
        requestValue,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchQuery.offset"],
        "request",
        `${discoverySchema}:DiscoverySearchQuery`,
        `${discoverySdk}:discoverySearch`,
        valueDefault("0", "The SDK always serializes zero when the offset is omitted"),
        notApplicable("This result index is a nonnegative safe integer, not a length-valued field"),
        requestValue,
        discoveryEvidence,
    ),
] as const

const discoveryResponseRules = [
    ...rules(
        [
            "DiscoveryApplication.guildId",
            "DiscoveryApplication.description",
            "DiscoveryApplication.categoryId",
            "DiscoveryApplication.primaryLanguage",
            "DiscoveryApplication.tags",
            "DiscoveryApplication.appliedAt",
            "DiscoveryApplication.reviewedAt",
            "DiscoveryApplication.reviewReason",
            "DiscoveryApplication.removedAt",
            "DiscoveryApplication.removalReason",
        ],
        "response",
        `${discoverySchema}:DiscoveryApplicationResponse`,
        `${discoverySdk}:application`,
        responseValue,
        unboundedResponse,
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryApplication.status"],
        "response",
        `${discoverySchema}:DiscoveryApplicationResponse`,
        `${discoverySdk}:application`,
        responseValue,
        bounded("UTF-16-code-units", 1, 100, "The SDK bounds the observed provider state string"),
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryApplication.guildNsfwLevel"],
        "response",
        `${discoverySchema}:DiscoveryApplicationResponse`,
        `${discoverySdk}:application`,
        omitted("An absent wire property stays omitted; explicit null and integers 0 through 3 are preserved"),
        scalar,
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryCategory.id"],
        "response",
        `${discoverySchema}:DiscoveryCategoryResponse`,
        `${discoverySdk}:discoveryCategories`,
        responseValue,
        scalar,
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryCategory.name"],
        "response",
        `${discoverySchema}:DiscoveryCategoryResponse`,
        `${discoverySdk}:discoveryCategories`,
        responseValue,
        bounded("UTF-16-code-units", 1, 200, "The SDK accepts category display names in this inclusive range"),
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryGuild.id", "DiscoveryGuild.name"],
        "response",
        `${discoverySchema}:DiscoveryGuildResponse`,
        `${discoverySdk}:discoveryGuild`,
        responseValue,
        unboundedResponse,
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        [
            "DiscoveryGuild.icon",
            "DiscoveryGuild.banner",
            "DiscoveryGuild.description",
            "DiscoveryGuild.primaryLanguage",
        ],
        "response",
        `${discoverySchema}:DiscoveryGuildResponse`,
        `${discoverySdk}:discoveryGuild`,
        valueDefault("null", "The SDK projects a nullish or absent provider property as null"),
        unboundedResponse,
        canonicalized("Nullish provider values are coalesced to a stable public null; strings are preserved"),
        discoveryEvidence,
    ),
    ...rules(
        [
            "DiscoveryGuild.categoryId",
            "DiscoveryGuild.memberCount",
            "DiscoveryGuild.onlineCount",
            "DiscoveryGuild.verificationLevel",
        ],
        "response",
        `${discoverySchema}:DiscoveryGuildResponse`,
        `${discoverySdk}:discoveryGuild`,
        responseValue,
        scalar,
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryGuild.tags", "DiscoveryGuild.features"],
        "response",
        `${discoverySchema}:DiscoveryGuildResponse`,
        `${discoverySdk}:discoveryGuild`,
        responseValue,
        unboundedResponse,
        providerView("The SDK validates string entries, copies the provider array, and freezes the public snapshot"),
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryCategoryCount.categoryId", "DiscoveryCategoryCount.count"],
        "response",
        `${discoverySchema}:DiscoveryCategoryCountResponse`,
        `${discoverySdk}:discoverySearch`,
        responseValue,
        scalar,
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchPage.guilds"],
        "response",
        `${discoverySchema}:DiscoveryGuildListResponse`,
        `${discoverySdk}:discoverySearch`,
        responseValue,
        bounded("items", 0, 48, "The SDK rejects a page exceeding the validated request limit, whose maximum is 48"),
        providerView("The SDK validates every entry, rejects duplicate identities, copies the array, and freezes it"),
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchPage.categoryCounts"],
        "response",
        `${discoverySchema}:DiscoveryGuildListResponse`,
        `${discoverySdk}:discoverySearch`,
        responseValue,
        bounded("items", 0, 9, "The SDK accepts each provider category ID from 0 through 8 at most once"),
        providerView("The SDK validates every entry, rejects duplicate category IDs, copies the array, and freezes it"),
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoverySearchPage.total"],
        "response",
        `${discoverySchema}:DiscoveryGuildListResponse`,
        `${discoverySdk}:discoverySearch`,
        responseValue,
        scalar,
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryStatus.application"],
        "response",
        `${discoverySchema}:DiscoveryStatusResponse`,
        `${discoverySdk}:discoveryStatus`,
        responseValue,
        notApplicable("This nullable object projection has no field-level length unit"),
        responseProjection,
        discoveryEvidence,
    ),
    ...rules(
        ["DiscoveryStatus.eligible", "DiscoveryStatus.minMemberCount"],
        "response",
        `${discoverySchema}:DiscoveryStatusResponse`,
        `${discoverySdk}:discoveryStatus`,
        responseValue,
        scalar,
        responseProjection,
        discoveryEvidence,
    ),
] as const

const memberRequestRules = [
    ...rules(
        ["MemberSearchQuery.query"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        optionalRequest,
        bounded("UTF-16-code-units", 0, 100, "The raw search string may be empty and is capped at 100 code units"),
        requestValue,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchQuery.limit"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        valueDefault("25", "The SDK serializes 25 when the explicit page limit is omitted"),
        bounded("items", 1, 100, "The requested result capacity is an integer in this inclusive range"),
        requestValue,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchQuery.offset"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        valueDefault("0", "The SDK serializes zero when the indexed-result offset is omitted"),
        notApplicable("This result index is a nonnegative safe integer, not a length-valued field"),
        requestValue,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchQuery.roleIds"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        optionalRequest,
        bounded("items", 0, 10, "At most ten unique decimal role IDs are accepted"),
        requestArray,
        memberEvidence,
    ),
    ...rules(
        [
            "MemberSearchQuery.joinedAtAfterSeconds",
            "MemberSearchQuery.joinedAtBeforeSeconds",
            "MemberSearchQuery.userCreatedAtAfterSeconds",
            "MemberSearchQuery.userCreatedAtBeforeSeconds",
        ],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        optionalRequest,
        bounded("seconds", 0, Number.MAX_SAFE_INTEGER, "The SDK accepts a nonnegative safe whole Unix-second value"),
        requestValue,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchQuery.joinSourceTypes", "MemberSearchQuery.sourceInviteCodes"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        optionalRequest,
        bounded("items", 0, 10, "At most ten unique values are accepted"),
        requestArray,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchQuery.isBot"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        optionalRequest,
        scalar,
        requestValue,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchQuery.sortBy"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        providerDefault("Omission uses Fluxer's indexed join-time ordering"),
        scalar,
        requestValue,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchQuery.sortOrder"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        `${memberSdk}:encodeMemberSearchQuery`,
        providerDefault("Omission uses Fluxer's descending order"),
        scalar,
        requestValue,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchIterationLimits.pageSize"],
        "request",
        `${memberSchema}:GuildMemberSearchRequest`,
        "src/internal/member-search-workflow.ts:searchMemberPagination",
        valueDefault("100", "Each traversal consumption defaults to the provider maximum of 100 hits per request"),
        bounded("items", 1, 100, "The per-request hit capacity is a positive safe integer in this range"),
        preserved(
            "The traversal passes the effective page size as the provider limit, reducing only the final request",
        ),
        memberIterationEvidence,
    ),
] as const

const memberResponseRules = [
    ...rules(
        [
            "MemberSearchHit.guildId",
            "MemberSearchHit.userId",
            "MemberSearchHit.username",
            "MemberSearchHit.globalName",
            "MemberSearchHit.nickname",
            "MemberSearchHit.sourceInviteCode",
            "MemberSearchHit.inviterId",
        ],
        "response",
        `${memberSchema}:GuildMemberSearchResult`,
        `${memberSdk}:hit`,
        responseValue,
        unboundedResponse,
        responseProjection,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchHit.discriminator"],
        "response",
        `${memberSchema}:GuildMemberSearchResult`,
        `${memberSdk}:hit`,
        responseValue,
        bounded("UTF-16-code-units", 4, 4, "The SDK requires exactly four decimal code units"),
        responseProjection,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchHit.roleIds"],
        "response",
        `${memberSchema}:GuildMemberSearchResult`,
        `${memberSdk}:hit`,
        responseValue,
        unboundedResponse,
        providerView("The SDK validates unique decimal IDs, copies them in provider order, and freezes the array"),
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchHit.joinedAtSeconds"],
        "response",
        `${memberSchema}:GuildMemberSearchResult`,
        `${memberSdk}:hit`,
        responseValue,
        bounded("seconds", 0, Number.MAX_SAFE_INTEGER, "The SDK requires a nonnegative safe whole Unix-second value"),
        responseProjection,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchHit.isBot"],
        "response",
        `${memberSchema}:GuildMemberSearchResult`,
        `${memberSdk}:hit`,
        responseValue,
        scalar,
        responseProjection,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchHit.joinSourceType"],
        "response",
        `${memberSchema}:GuildMemberSearchSupplemental`,
        `${memberSdk}:hit`,
        valueDefault("null", "The SDK converts an absent or null supplemental source to public null"),
        scalar,
        canonicalized("A missing or null provider value becomes null; known numeric source values are preserved"),
        memberEvidence,
    ),
    ...rules(
        [
            "MemberSearchPage.guildId",
            "MemberSearchPage.pageResultCount",
            "MemberSearchPage.totalResultCount",
            "MemberSearchPage.indexing",
        ],
        "response",
        `${memberSchema}:GuildMemberSearchResponse`,
        `${memberSdk}:decodeMemberSearchPage`,
        responseValue,
        scalar,
        responseProjection,
        memberEvidence,
    ),
    ...rules(
        ["MemberSearchPage.members"],
        "response",
        `${memberSchema}:GuildMemberSearchResponse`,
        `${memberSdk}:decodeMemberSearchPage`,
        responseValue,
        bounded("items", 0, 100, "The SDK rejects a page exceeding the validated request limit, whose maximum is 100"),
        providerView(
            "The SDK validates the complete page, rejects duplicate user IDs, copies the array, and freezes it",
        ),
        memberEvidence,
    ),
] as const

const messageRequestRules = [
    ...rules(
        ["MessageSearchContext.guildId", "MessageSearchContext.channelId"],
        "request",
        `${messageRequestSchema}:GlobalSearchMessagesRequest`,
        `${messageSdk}:encodeMessageSearch`,
        omitted("Either context ID may be omitted only when the other decimal ID supplies the required search context"),
        notApplicable("A decimal snowflake format is enforced, but no string-length bound is published"),
        preserved("The SDK captures the decimal ID once and serializes it under the corresponding context wire key"),
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.limit"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        valueDefault("25", "The SDK always serializes 25 as hits_per_page when omitted"),
        bounded("items", 1, 25, "The requested message capacity is an integer in this inclusive range"),
        requestValue,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.page"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        valueDefault("1", "The SDK always serializes the first page when omitted"),
        notApplicable("This numbered-page scalar is restricted to integers 1 through 400, not a length unit"),
        requestValue,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.maxId", "MessageSearchQuery.minId"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        notApplicable("A decimal snowflake format is enforced, but no string-length bound is published"),
        requestValue,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.content"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("UTF-16-code-units", 1, 1024, "The SDK enforces this inclusive raw search-text bound"),
        requestValue,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.contents"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 100, "At most 100 strings are accepted, each containing 1 through 1,024 UTF-16 code units"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.exactPhrases"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 10, "At most ten strings are accepted, each containing 1 through 1,024 UTF-16 code units"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.channelIds", "MessageSearchQuery.excludeChannelIds"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 500, "At most 500 decimal channel IDs are accepted"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.authorTypes", "MessageSearchQuery.excludeAuthorTypes"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 20, "At most 20 supported author-category literals are accepted"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        [
            "MessageSearchQuery.authorIds",
            "MessageSearchQuery.excludeAuthorIds",
            "MessageSearchQuery.mentions",
            "MessageSearchQuery.excludeMentions",
        ],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 100, "At most 100 decimal user IDs are accepted"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.mentionedEveryone", "MessageSearchQuery.pinned"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        scalar,
        requestValue,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.has", "MessageSearchQuery.excludeHas"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 20, "At most 20 supported content-category literals are accepted"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.embedTypes", "MessageSearchQuery.excludeEmbedTypes"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 20, "At most 20 supported embed-category literals are accepted"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.embedProviders", "MessageSearchQuery.excludeEmbedProviders"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 50, "At most 50 strings are accepted, each containing 1 through 256 UTF-16 code units"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.linkHostnames", "MessageSearchQuery.excludeLinkHostnames"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 100, "At most 100 strings are accepted, each containing 1 through 255 UTF-16 code units"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.attachmentFilenames", "MessageSearchQuery.excludeAttachmentFilenames"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 100, "At most 100 strings are accepted, each containing 1 through 1,024 UTF-16 code units"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.attachmentExtensions", "MessageSearchQuery.excludeAttachmentExtensions"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        optionalRequest,
        bounded("items", 0, 50, "At most 50 strings are accepted, each containing 1 through 32 UTF-16 code units"),
        requestArray,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.sortBy"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        providerDefault("The SDK omits this property and the pinned provider schema applies timestamp ordering"),
        scalar,
        requestValue,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.sortOrder"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        providerDefault("The SDK omits this property and the pinned provider schema applies descending order"),
        scalar,
        requestValue,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchQuery.includeNsfw"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        `${messageSdk}:encodeMessageSearch`,
        providerDefault(
            "The SDK omits this property and the pinned provider schema defaults to excluding NSFW results",
        ),
        scalar,
        requestValue,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchIterationLimits.pageSize"],
        "request",
        `${messageRequestSchema}:MessageSearchRequest`,
        "src/internal/message-search-workflow.ts:searchMessagePagination",
        valueDefault("25", "Each traversal consumption defaults to 25 messages per request"),
        bounded("items", 1, 25, "The per-request message capacity is a positive safe integer in this range"),
        preserved("The traversal sends the smaller of pageSize and maxItems as hits_per_page for every numbered page"),
        messageIterationEvidence,
    ),
] as const

const messageResponseRules = [
    ...rules(
        ["MessageSearchChannel.id", "MessageSearchChannel.type"],
        "response",
        "packages/schema/src/domains/channel/ChannelSchemas.ts:ChannelResponse",
        `${messageSdk}:channel`,
        responseValue,
        scalar,
        responseProjection,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchChannel.guildId", "MessageSearchChannel.name"],
        "response",
        "packages/schema/src/domains/channel/ChannelSchemas.ts:ChannelResponse",
        `${messageSdk}:channel`,
        omitted("An absent optional provider property remains omitted from the projected search-channel snapshot"),
        unboundedResponse,
        providerView("The SDK validates the optional provider string, projects its public key, and preserves absence"),
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchPage.messages"],
        "response",
        `${messageResponseSchema}:MessageSearchResultsResponse`,
        `${messageSdk}:decodeMessageSearchPage`,
        responseValue,
        bounded("items", 0, 25, "The SDK rejects a result array longer than the validated hits_per_page maximum of 25"),
        providerView(
            "The configured message decoder projects every entry, then the SDK copies and freezes the result array",
        ),
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchPage.channels"],
        "response",
        `${messageResponseSchema}:MessageSearchResultsResponse`,
        `${messageSdk}:decodeMessageSearchPage`,
        responseValue,
        bounded(
            "items",
            0,
            25,
            "Exactly one channel is required per distinct result channel, so at most 25 are accepted",
        ),
        providerView(
            "The SDK projects unique channels, requires their IDs to match the result messages exactly, and freezes the array",
        ),
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchPage.total", "MessageSearchPage.page"],
        "response",
        `${messageResponseSchema}:MessageSearchResultsResponse`,
        `${messageSdk}:decodeMessageSearchPage`,
        responseValue,
        notApplicable("This bounded integer observation is not measured by a length unit"),
        responseProjection,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchPage.hitsPerPage"],
        "response",
        `${messageResponseSchema}:MessageSearchResultsResponse`,
        `${messageSdk}:decodeMessageSearchPage`,
        responseValue,
        bounded("items", 1, 25, "The provider-reported page capacity must be an integer in this inclusive range"),
        responseProjection,
        messageEvidence,
    ),
    ...rules(
        ["MessageSearchPage.indexing"],
        "response",
        `${messageResponseSchema}:MessageSearchIndexingResponse`,
        `${messageSdk}:decodeMessageSearchPage`,
        valueDefault(
            "false",
            "An indexing response supplies true; a result response omits the wire key and the SDK supplies false",
        ),
        scalar,
        canonicalized(
            "The indexing literal true is preserved, while the result branch is discriminated with an SDK-supplied false",
        ),
        messageEvidence,
    ),
] as const

export const searchFieldRules = defineFieldRules([
    ...discoveryRequestRules,
    ...discoveryResponseRules,
    ...memberRequestRules,
    ...memberResponseRules,
    ...messageRequestRules,
    ...messageResponseRules,
])

export const searchLocalFieldExclusions = defineLocalFieldExclusions([
    ...["DiscoverySearchPage.offset", "DiscoverySearchPage.limit"].map((target) => ({
        target,
        direction: "response" as const,
        rationale:
            "The provider page omits this field; the SDK exposes the validated effective request value beside the volatile result",
        sdkOwner: `${discoverySdk}:discoverySearch` as const,
        executableEvidence: discoveryEvidence,
    })),
    ...["MemberSearchIterationLimits.maxItems", "MemberSearchIterationLimits.maxPages"].map((target) => ({
        target,
        direction: "request" as const,
        rationale: "This is an SDK-local traversal budget and is never serialized as a provider request field",
        sdkOwner: "src/internal/member-search-workflow.ts:searchMemberPagination" as const,
        executableEvidence: memberIterationEvidence,
    })),
    ...["MessageSearchIterationLimits.maxItems", "MessageSearchIterationLimits.maxPages"].map((target) => ({
        target,
        direction: "request" as const,
        rationale: "This is an SDK-local traversal budget and is never serialized as a provider request field",
        sdkOwner: "src/internal/message-search-workflow.ts:searchMessagePagination" as const,
        executableEvidence: messageIterationEvidence,
    })),
])
