import {
    defineFieldRules,
    defineLocalFieldExclusions,
    type FieldDirection,
    type FieldRuleAnnotation,
} from "./conformance-fields-registry.js"

const oauthEvidence = ["tests/oauth.test.ts", "tests/oauth-input-boundaries.test.ts"] as const
const userEvidence = ["tests/users.test.ts", "tests/user-profiles.test.ts"] as const
const userTextEvidence = ["tests/users.test.ts", "tests/text-validation.test.ts"] as const
const webhookEvidence = ["tests/webhooks.test.ts", "tests/input-validation.test.ts"] as const
const webhookMessageEvidence = ["tests/webhooks.test.ts", "tests/message-fields.test.ts"] as const

const omitted = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "omitted", detail })
const noDefault = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "none", detail })
const providerDefault = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "provider", detail })
const valueDefault = (value: string, detail: string): FieldRuleAnnotation["default"] => ({
    kind: "value",
    value,
    detail,
})
const notApplicable = (detail: string): FieldRuleAnnotation["length"] => ({
    kind: "not-applicable",
    detail,
})
const bounded = (
    unit: Extract<FieldRuleAnnotation["length"], { kind: "bounded" }>["unit"],
    minimum: number | undefined,
    maximum: number | undefined,
    detail: string,
): FieldRuleAnnotation["length"] => ({
    kind: "bounded",
    unit,
    ...(minimum === undefined ? {} : { minimum }),
    ...(maximum === undefined ? {} : { maximum }),
    detail,
})
const preserved = (detail: string): FieldRuleAnnotation["normalization"] => ({ kind: "preserved", detail })
const canonicalized = (detail: string): FieldRuleAnnotation["normalization"] => ({
    kind: "canonicalized",
    detail,
})
const providerView = (detail: string): FieldRuleAnnotation["normalization"] => ({
    kind: "provider-normalized-view",
    detail,
})

function rule(
    target: string,
    direction: FieldDirection,
    providerOwner: FieldRuleAnnotation["providerOwner"],
    sdkOwner: FieldRuleAnnotation["sdkOwner"],
    executableEvidence: FieldRuleAnnotation["executableEvidence"],
    defaultRule: FieldRuleAnnotation["default"],
    length: FieldRuleAnnotation["length"] = notApplicable(
        "The field is scalar or the pinned provider contract publishes no field-specific length bound",
    ),
    normalization: FieldRuleAnnotation["normalization"] = preserved(
        "The SDK preserves the validated value while renaming only its public or wire key when necessary",
    ),
): FieldRuleAnnotation {
    return {
        target,
        direction,
        providerOwner,
        sdkOwner,
        default: defaultRule,
        length,
        normalization,
        executableEvidence,
    }
}

function rules(
    targets: readonly string[],
    direction: FieldDirection,
    providerOwner: FieldRuleAnnotation["providerOwner"],
    sdkOwner: FieldRuleAnnotation["sdkOwner"],
    executableEvidence: FieldRuleAnnotation["executableEvidence"],
    defaultRule: FieldRuleAnnotation["default"],
    length?: FieldRuleAnnotation["length"],
    normalization?: FieldRuleAnnotation["normalization"],
): readonly FieldRuleAnnotation[] {
    return targets.map((target) =>
        rule(target, direction, providerOwner, sdkOwner, executableEvidence, defaultRule, length, normalization),
    )
}

const optionalRequest = omitted("An absent optional public property is not serialized")
const requiredRequest = noDefault("The public request field is required and has no SDK or provider default")
const requiredResponse = noDefault("A valid provider observation must supply this field")
const optionalResponse = omitted("The SDK preserves provider absence instead of synthesizing the optional field")
const responseProjection = providerView(
    "The SDK validates the provider value, renames its wire key when needed, and freezes the projected snapshot",
)
const unboundedResponse = notApplicable(
    "Neither the pinned provider response schema nor the SDK projector declares a public response-length bound",
)
const scalarLength = notApplicable("This scalar or structured field has no applicable variable-length bound")

const oauthRequestRules: readonly FieldRuleAnnotation[] = [
    rule(
        "OAuthAuthorizationInput.redirectUri",
        "request",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:AuthorizeRequest.redirect_uri",
        "src/internal/oauth.ts:redirectUri",
        oauthEvidence,
        requiredRequest,
        bounded("UTF-16-code-units", 1, 256, "The SDK applies its defensive cap before URL parsing"),
        preserved("Accepted HTTPS or loopback-HTTP text is serialized exactly; noncanonical text is rejected"),
    ),
    rule(
        "OAuthAuthorizationInput.scopes",
        "request",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:AuthorizeRequest.scope",
        "src/internal/oauth.ts:OAuthOwner.authorizationUrl",
        oauthEvidence,
        requiredRequest,
        bounded("items", 1, 256, "Supplied entries, including duplicates, count toward the SDK defensive limit"),
        canonicalized("Duplicate scopes are removed in first-occurrence order and the result is joined with spaces"),
    ),
    rule(
        "OAuthAuthorizationInput.state",
        "request",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:AuthorizeRequest.state",
        "src/internal/oauth.ts:canonicalText",
        oauthEvidence,
        requiredRequest,
        bounded("UTF-16-code-units", 1, 256, "The SDK requires well-formed canonical UTF-16 text"),
        preserved("Accepted state is serialized exactly; surrounding whitespace, U+000C and U+202E are rejected"),
    ),
    rule(
        "OAuthAuthorizationInput.codeChallenge",
        "request",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:AuthorizeRequest.code_challenge",
        "src/internal/oauth.ts:OAuthOwner.authorizationUrl",
        oauthEvidence,
        requiredRequest,
        bounded("UTF-16-code-units", 43, 43, "The SDK accepts exactly 43 ASCII base64url characters"),
        preserved("The validated S256 challenge is serialized unchanged"),
    ),
    ...[
        [
            "OAuthAuthorizationInput.guildId",
            "packages/schema/src/domains/oauth/OAuthSchemas.ts:AuthorizeRequest.guild_id",
        ],
        [
            "OAuthAuthorizationInput.channelId",
            "packages/schema/src/domains/oauth/OAuthSchemas.ts:AuthorizeRequest.channel_id",
        ],
    ].map(([target, owner]) =>
        rule(
            target!,
            "request",
            owner! as FieldRuleAnnotation["providerOwner"],
            "src/internal/oauth.ts:OAuthOwner.authorizationUrl",
            oauthEvidence,
            optionalRequest,
            scalarLength,
            preserved("The decimal ID is serialized unchanged after bot-scope and mutual-exclusion checks"),
        ),
    ),
    rule(
        "OAuthAuthorizationInput.permissions",
        "request",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:AuthorizeRequest.permissions",
        "src/internal/oauth.ts:OAuthOwner.authorizationUrl",
        oauthEvidence,
        optionalRequest,
        scalarLength,
        canonicalized("An accepted unsigned 64-bit bigint is serialized as its decimal provider parameter"),
    ),
    rule(
        "OAuthAuthorizationInput.disableGuildSelect",
        "request",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:AuthorizeRequest.disable_guild_select",
        "src/internal/oauth.ts:OAuthOwner.authorizationUrl",
        oauthEvidence,
        optionalRequest,
        scalarLength,
        canonicalized("The boolean becomes the provider query literal true or false"),
    ),
    ...[
        ["OAuthCodeExchangeInput.code", "packages/schema/src/domains/oauth/OAuthSchemas.ts:TokenRequest.code"],
        [
            "OAuthCodeExchangeInput.redirectUri",
            "packages/schema/src/domains/oauth/OAuthSchemas.ts:TokenRequest.redirect_uri",
        ],
    ].map(([target, owner]) =>
        rule(
            target!,
            "request",
            owner! as FieldRuleAnnotation["providerOwner"],
            target!.endsWith("redirectUri")
                ? "src/internal/oauth.ts:redirectUri"
                : "src/internal/oauth.ts:canonicalText",
            oauthEvidence,
            requiredRequest,
            bounded("UTF-16-code-units", 1, 256, "The SDK applies its defensive canonical-text cap"),
            preserved("Accepted text is form-encoded without rewriting its value; noncanonical text is rejected"),
        ),
    ),
    rule(
        "OAuthCodeExchangeInput.codeVerifier",
        "request",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:TokenRequest.code_verifier",
        "src/internal/oauth.ts:OAuthOwner.exchangeCode",
        oauthEvidence,
        requiredRequest,
        bounded(
            "UTF-16-code-units",
            43,
            128,
            "Only ASCII letters, digits and RFC 7636 unreserved - . _ ~ are accepted",
        ),
        preserved("The validated PKCE verifier is form-encoded unchanged"),
    ),
]

const oauthResponseRules: readonly FieldRuleAnnotation[] = [
    ...rules(
        ["OAuthTokens.accessToken", "OAuthTokens.refreshToken"],
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2TokenResponse",
        "src/internal/oauth.ts:token",
        oauthEvidence,
        requiredResponse,
        bounded("UTF-16-code-units", 1, undefined, "The SDK rejects an empty credential; no maximum is published"),
        responseProjection,
    ),
    ...rules(
        ["OAuthTokens.tokenType", "OAuthTokens.expiresInSeconds"],
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2TokenResponse",
        "src/internal/oauth.ts:token",
        oauthEvidence,
        requiredResponse,
        scalarLength,
        responseProjection,
    ),
    rule(
        "OAuthTokens.scopes",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2TokenResponse.scope",
        "src/internal/oauth.ts:token",
        oauthEvidence,
        requiredResponse,
        unboundedResponse,
        canonicalized(
            "The provider space-or-plus-separated scope string becomes a frozen array with empty segments removed",
        ),
    ),
    ...rules(
        ["OAuthIdentity.id", "OAuthIdentity.discriminator", "OAuthIdentity.globalName", "OAuthIdentity.avatar"],
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2UserInfoResponse",
        "src/internal/oauth.ts:identity",
        oauthEvidence,
        requiredResponse,
        unboundedResponse,
        responseProjection,
    ),
    rule(
        "OAuthIdentity.username",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2UserInfoResponse.username",
        "src/internal/oauth.ts:identity",
        oauthEvidence,
        requiredResponse,
        bounded("UTF-16-code-units", 1, undefined, "The SDK rejects an empty username; no maximum is published"),
        responseProjection,
    ),
    ...rules(
        ["OAuthIdentity.email", "OAuthIdentity.verified"],
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2UserInfoResponse",
        "src/internal/oauth.ts:identity",
        oauthEvidence,
        optionalResponse,
        unboundedResponse,
        responseProjection,
    ),
    ...rules(
        [
            "OAuthConnection.id",
            "OAuthConnection.name",
            "OAuthConnection.type",
            "OAuthConnection.verified",
            "OAuthConnection.visibilityFlags",
            "OAuthConnection.sortOrder",
        ],
        "response",
        "packages/schema/src/domains/connection/ConnectionSchemas.ts:ConnectionResponse",
        "src/internal/oauth.ts:connections",
        oauthEvidence,
        requiredResponse,
        unboundedResponse,
        responseProjection,
    ),
    rule(
        "OAuthIntrospection.active",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2IntrospectResponse.active",
        "src/internal/oauth.ts:introspection",
        oauthEvidence,
        requiredResponse,
        scalarLength,
        preserved("The SDK preserves the provider boolean and projects inactive responses to the false-only variant"),
    ),
    rule(
        "OAuthIntrospection.clientId",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2IntrospectResponse.client_id",
        "src/internal/oauth.ts:introspection",
        oauthEvidence,
        noDefault("The active introspection variant requires the provider client_id field"),
        scalarLength,
        responseProjection,
    ),
    rule(
        "OAuthIntrospection.subjectId",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2IntrospectResponse.sub",
        "src/internal/oauth.ts:introspection",
        oauthEvidence,
        omitted("The active introspection variant omits subjectId when the provider omits sub"),
        scalarLength,
        responseProjection,
    ),
    rule(
        "OAuthIntrospection.tokenType",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2IntrospectResponse.token_type",
        "src/internal/oauth.ts:introspection",
        oauthEvidence,
        noDefault("The active introspection variant requires Bearer or refresh_token from the provider"),
        scalarLength,
        responseProjection,
    ),
    rule(
        "OAuthIntrospection.scopes",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2IntrospectResponse.scope",
        "src/internal/oauth.ts:introspection",
        oauthEvidence,
        noDefault("The active introspection variant requires the provider scope string"),
        unboundedResponse,
        canonicalized(
            "The SDK splits the provider scope string on whitespace or plus signs and freezes nonempty entries",
        ),
    ),
    rule(
        "OAuthIntrospection.issuedAtUnixSeconds",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2IntrospectResponse.iat",
        "src/internal/oauth.ts:introspection",
        oauthEvidence,
        noDefault("The active introspection variant requires a nonnegative safe-integer provider iat value"),
        scalarLength,
        responseProjection,
    ),
    rule(
        "OAuthIntrospection.expiresAtUnixSeconds",
        "response",
        "packages/schema/src/domains/oauth/OAuthSchemas.ts:OAuth2IntrospectResponse.exp",
        "src/internal/oauth.ts:introspection",
        oauthEvidence,
        omitted("The active introspection variant omits expiresAtUnixSeconds when the provider omits exp"),
        scalarLength,
        responseProjection,
    ),
]

const userRequestRules: readonly FieldRuleAnnotation[] = [
    rule(
        "UserProfileQuery.guildId",
        "request",
        "packages/schema/src/domains/user/UserRequestSchemas.ts:UserProfileQueryRequest.guild_id",
        "src/internal/users.ts:userProfile",
        userEvidence,
        optionalRequest,
        scalarLength,
        preserved("The validated decimal ID is encoded as the guild_id query parameter"),
    ),
    rule(
        "DirectMessageGroupEdit.name",
        "request",
        "packages/schema/src/domains/channel/ChannelRequestSchemas.ts:ChannelUpdateGroupDmRequest.name",
        "src/internal/field-text.ts:channelName",
        userTextEvidence,
        optionalRequest,
        bounded(
            "UTF-16-code-units",
            1,
            100,
            "The provider-normalized view is 1-100 units; the SDK also rejects raw input over 10,000 units",
        ),
        providerView(
            "Validation uses Fluxer general-name preprocessing, while the accepted original string or explicit null is serialized",
        ),
    ),
    rule(
        "DirectMessageGroupEdit.icon",
        "request",
        "packages/schema/src/domains/channel/ChannelRequestSchemas.ts:ChannelUpdateGroupDmRequest.icon",
        "src/internal/users.ts:directMessageEdit",
        userEvidence,
        optionalRequest,
        bounded("bytes", 1, 10_485_760, "The bound applies to decoded avatar image data; null clears the icon"),
        preserved("The SDK validates the data-URI form and serializes the original string or explicit null"),
    ),
    rule(
        "DirectMessageGroupEdit.ownerId",
        "request",
        "packages/schema/src/domains/channel/ChannelRequestSchemas.ts:ChannelUpdateGroupDmRequest.owner_id",
        "src/internal/users.ts:directMessageEdit",
        userEvidence,
        optionalRequest,
        scalarLength,
        preserved("The decimal ID is serialized unchanged as owner_id"),
    ),
    rule(
        "DirectMessageGroupEdit.nicknames",
        "request",
        "packages/schema/src/domains/channel/ChannelSchemas.ts:ChannelNicknameOverrides",
        "src/internal/field-text.ts:normalizedText",
        userTextEvidence,
        optionalRequest,
        bounded(
            "UTF-16-code-units",
            0,
            32,
            "The bound applies independently to each provider-normalized nickname value",
        ),
        providerView(
            "Each nonempty raw nickname is checked after U+000C/U+202E removal and outer trimming, then serialized unchanged; null clears",
        ),
    ),
]

const userResponseRules: readonly FieldRuleAnnotation[] = [
    ...rules(
        [
            "User.id",
            "User.username",
            "User.discriminator",
            "User.displayName",
            "User.avatar",
            "User.avatarColor",
            "User.flags",
        ],
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserPartialResponse",
        "src/internal/users.ts:decodeUser",
        userEvidence,
        requiredResponse,
        unboundedResponse,
        responseProjection,
    ),
    ...rules(
        ["User.isBot", "User.isSystem"],
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserPartialResponse",
        "src/internal/users.ts:decodeUser",
        userEvidence,
        valueDefault("false", "An omitted provider bot or system marker decodes to false"),
        scalarLength,
        responseProjection,
    ),
    ...rules(
        ["UserProfile.user", "UserProfile.profile"],
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserProfileFullResponse",
        "src/internal/users.ts:userProfile",
        userEvidence,
        requiredResponse,
        scalarLength,
        responseProjection,
    ),
    rule(
        "UserProfile.guildProfile",
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:GuildMemberProfileDataResponse",
        "src/internal/users.ts:userProfile",
        userEvidence,
        valueDefault("null", "An absent or explicit-null provider guild profile projects to null"),
        scalarLength,
        responseProjection,
    ),
    rule(
        "UserProfile.isLimited",
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserProfileFullResponse.profile_limited",
        "src/internal/users.ts:userProfile",
        userEvidence,
        valueDefault("false", "Only provider literal true projects to true; omission projects to false"),
        scalarLength,
        responseProjection,
    ),
    ...rules(
        [
            "UserProfileFields.bio",
            "UserProfileFields.pronouns",
            "UserProfileFields.banner",
            "UserProfileFields.accentColor",
        ],
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserProfileDataResponse",
        "src/internal/users.ts:decodeUserProfileFields",
        userEvidence,
        requiredResponse,
        unboundedResponse,
        responseProjection,
    ),
    rule(
        "UserProfileFields.bannerColor",
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserProfileDataResponse.banner_color",
        "src/internal/users.ts:decodeUserProfileFields",
        userEvidence,
        optionalResponse,
        scalarLength,
        responseProjection,
    ),
    ...rules(
        ["DirectMessageChannel.id", "DirectMessageChannel.type"],
        "response",
        "packages/schema/src/domains/channel/ChannelSchemas.ts:ChannelResponse",
        "src/internal/users.ts:decodeDirectMessage",
        userEvidence,
        requiredResponse,
        scalarLength,
        responseProjection,
    ),
    rule(
        "DirectMessageChannel.recipients",
        "response",
        "packages/schema/src/domains/channel/ChannelSchemas.ts:ChannelResponse.recipients",
        "src/internal/users.ts:decodeDirectMessage",
        userEvidence,
        valueDefault(
            "[]",
            "An omitted group-DM recipient list projects to an empty frozen array; DMs require the list",
        ),
        bounded("items", 0, 49, "Fluxer publishes MAX_GROUP_DM_OTHER_RECIPIENTS as the response maximum"),
        responseProjection,
    ),
    ...rules(
        [
            "DirectMessageChannel.name",
            "DirectMessageChannel.icon",
            "DirectMessageChannel.ownerId",
            "DirectMessageChannel.lastMessageId",
        ],
        "response",
        "packages/schema/src/domains/channel/ChannelSchemas.ts:ChannelResponse",
        "src/internal/users.ts:decodeDirectMessage",
        userEvidence,
        valueDefault("null", "A nullish or absent provider field projects to explicit null"),
        unboundedResponse,
        responseProjection,
    ),
    rule(
        "DirectMessageChannel.nicknames",
        "response",
        "packages/schema/src/domains/channel/ChannelSchemas.ts:ChannelResponse.nicks",
        "src/internal/users.ts:decodeDirectMessage",
        userEvidence,
        valueDefault("{}", "An omitted provider nickname record projects to an empty frozen record"),
        bounded("UTF-16-code-units", 1, 32, "The bound applies independently to every returned nickname value"),
        responseProjection,
    ),
    rule(
        "DirectMessageLatestMessages.messages",
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:PreloadMessagesResponse",
        "src/internal/users.ts:directMessageLatestMessages",
        userEvidence,
        requiredResponse,
        bounded("items", 0, 100, "The provider response is keyed only by the SDK's at-most-100 requested channel IDs"),
        providerView(
            "The provider record is validated and wrapped as the frozen messages property without filling omissions",
        ),
    ),
]

const userGatewayRules: readonly FieldRuleAnnotation[] = rules(
    ["DirectMessageRecipientChange.channelId", "DirectMessageRecipientChange.userId"],
    "gateway",
    "fluxer_docs/src/content/docs/gateway/events.md#CHANNEL_RECIPIENT_ADD",
    "src/internal/gateway.ts:runSelectedGateway",
    userEvidence,
    requiredResponse,
    scalarLength,
    canonicalized("The gateway channel_id and nested user.id are projected to flat decimal-string fields"),
)

const webhookRequestRules: readonly FieldRuleAnnotation[] = [
    rule(
        "DefaultWebhookOperationOptions.auditReason",
        "request",
        "packages/schema/src/primitives/ChannelValidators.ts:AuditLogReasonType",
        "src/internal/webhooks.ts:audit",
        webhookEvidence,
        optionalRequest,
        bounded("UTF-16-code-units", 1, 512, "Only printable ASCII is accepted and the bound applies after trimming"),
        canonicalized("The SDK trims surrounding ASCII whitespace before setting X-Audit-Log-Reason"),
    ),
    rule(
        "WebhookCreate.avatar",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookCreateRequest.avatar",
        "src/internal/webhooks.ts:settings",
        webhookEvidence,
        providerDefault("Omission creates the webhook without a custom avatar"),
        bounded(
            "bytes",
            1,
            10_485_760,
            "The provider bound applies to decoded avatar image data; null also selects the default",
        ),
        preserved("The SDK validates data-URI syntax and serializes the original string or explicit null"),
    ),
    rule(
        "WebhookEdit.avatar",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookUpdateRequest.avatar",
        "src/internal/webhooks.ts:settings",
        webhookEvidence,
        optionalRequest,
        bounded("bytes", 1, 10_485_760, "The provider bound applies to decoded avatar data; null clears it"),
        preserved("The SDK validates data-URI syntax and serializes the original string or explicit null"),
    ),
    rule(
        "WebhookTokenEdit.avatar",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookTokenUpdateRequest.avatar",
        "src/internal/webhooks.ts:settings",
        webhookEvidence,
        optionalRequest,
        bounded("bytes", 1, 10_485_760, "The provider bound applies to decoded avatar data; null clears it"),
        preserved("The SDK validates data-URI syntax and serializes the original string or explicit null"),
    ),
    rule(
        "WebhookEdit.channelId",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookUpdateRequest.channel_id",
        "src/internal/webhooks.ts:settings",
        webhookEvidence,
        optionalRequest,
        scalarLength,
        preserved("The validated decimal ID is serialized unchanged as channel_id"),
    ),
    ...[
        [
            "WebhookMessageInput.allowedMentions",
            "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageRequest.allowed_mentions",
        ],
        [
            "WebhookMessageEdit.allowedMentions",
            "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageEditRequest.allowed_mentions",
        ],
    ].map(([target, owner]) =>
        rule(
            target!,
            "request",
            owner! as FieldRuleAnnotation["providerOwner"],
            "src/internal/message.ts:encodeAllowedMentions",
            webhookMessageEvidence,
            valueDefault(
                "no notifications",
                "Omission serializes empty users, roles and parse arrays plus replied_user false",
            ),
            scalarLength,
            canonicalized("The SDK serializes a complete restrictive provider allowed_mentions object"),
        ),
    ),
    rule(
        "WebhookMessageInput.attachments",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageRequest.attachments",
        "src/internal/attachments.ts:encodeAttachments",
        webhookMessageEvidence,
        optionalRequest,
        bounded(
            "items",
            0,
            10,
            "The pinned provider fallback is ten attachments per message; instance limit configuration may replace it",
        ),
        canonicalized("Local byte sources become provider attachment metadata and uploads in caller order"),
    ),
    rule(
        "WebhookMessageInput.content",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageRequest.content",
        "src/internal/message.ts:encodeBody",
        webhookMessageEvidence,
        optionalRequest,
        bounded(
            "UTF-16-code-units",
            0,
            4000,
            "The pinned default webhook limit is 4,000 JavaScript string length units; instance configuration may replace it",
        ),
        preserved("Message content is serialized without trimming or rewriting"),
    ),
    rule(
        "WebhookMessageInput.embeds",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageRequest.embeds",
        "src/internal/message.ts:encodeBody",
        webhookMessageEvidence,
        optionalRequest,
        bounded(
            "items",
            0,
            10,
            "The pinned provider fallback is ten embeds per message; instance limit configuration may replace it",
        ),
        canonicalized("Each embed is validated and projected to provider wire shape in caller order"),
    ),
    rule(
        "WebhookMessageInput.stickerIds",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageRequest.sticker_ids",
        "src/internal/message.ts:encodeMessage",
        webhookMessageEvidence,
        optionalRequest,
        bounded("items", 0, 3, "Fluxer accepts at most three sticker IDs"),
        preserved("The SDK snapshots decimal sticker IDs in caller order and serializes them as sticker_ids"),
    ),
    rule(
        "WebhookMessageInput.avatarUrl",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageRequest.avatar_url",
        "src/internal/webhooks.ts:webhookSend",
        webhookEvidence,
        optionalRequest,
        bounded("UTF-16-code-units", 1, 8192, "The SDK defensive cap applies before HTTP(S)-URL parsing"),
        preserved("An accepted credential-free HTTP(S) URL is serialized unchanged as avatar_url"),
    ),
    rule(
        "WebhookMessageInput.flags",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageRequest.flags",
        "src/internal/webhooks.ts:webhookSend",
        webhookMessageEvidence,
        providerDefault("Fluxer's webhook-message schema defaults an omitted flags field to zero"),
        scalarLength,
        preserved("Accepted SuppressEmbeds and SuppressNotifications bits are serialized as the same integer"),
    ),
    rule(
        "WebhookMessageEdit.flags",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageEditRequest.flags",
        "src/internal/webhooks.ts:webhookMessage",
        webhookMessageEvidence,
        omitted("Omission leaves the existing message flags unchanged"),
        scalarLength,
        preserved("Accepted SuppressEmbeds and SuppressNotifications bits are serialized as the same integer"),
    ),
    rule(
        "WebhookMessageEdit.content",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageEditRequest.content",
        "src/internal/message.ts:encodeEdit",
        webhookMessageEvidence,
        omitted("Omission leaves existing content unchanged; an empty string clears it"),
        bounded(
            "UTF-16-code-units",
            0,
            4000,
            "The pinned default webhook limit is 4,000 JavaScript string length units; instance configuration may replace it",
        ),
        preserved("Message content is serialized without trimming or rewriting"),
    ),
    rule(
        "WebhookMessageEdit.embeds",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageEditRequest.embeds",
        "src/internal/message.ts:encodeEdit",
        webhookMessageEvidence,
        omitted("Omission leaves existing embeds unchanged; an empty array clears them"),
        bounded("items", 0, 10, "The pinned provider fallback is ten embeds per message"),
        canonicalized("Each embed is validated and projected to provider wire shape in caller order"),
    ),
    rule(
        "WebhookMessageInput.messageReference",
        "request",
        "packages/schema/src/domains/webhook/WebhookRequestSchemas.ts:WebhookMessageRequest.message_reference",
        "src/internal/webhooks.ts:webhookSend",
        webhookMessageEvidence,
        optionalRequest,
        scalarLength,
        canonicalized("The discriminated public reply or forward wrapper becomes the provider message-reference shape"),
    ),
    ...rules(
        ["WebhookReplyReference.type", "WebhookForwardReference.type"],
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:MessageReferenceRequest.type",
        "src/internal/webhooks.ts:webhookSend",
        webhookMessageEvidence,
        requiredRequest,
        scalarLength,
        canonicalized("The public reply or forward discriminator selects provider numeric reference type 0 or 1"),
    ),
    rule(
        "WebhookReplyReference.target",
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:MessageReferenceRequest",
        "src/internal/webhooks.ts:webhookSend",
        webhookMessageEvidence,
        requiredRequest,
        scalarLength,
        canonicalized("The required id and channelId are serialized as message_id and channel_id with type 0"),
    ),
    rule(
        "WebhookForwardReference.source",
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:MessageReferenceRequest",
        "src/internal/webhooks.ts:webhookSend",
        webhookMessageEvidence,
        requiredRequest,
        scalarLength,
        canonicalized("The ForwardMessageInput is validated and serialized as a type-1 provider reference"),
    ),
]

const webhookResponseRules: readonly FieldRuleAnnotation[] = [
    ...rules(
        ["Webhook.id", "Webhook.guildId", "Webhook.channelId", "Webhook.name"],
        "response",
        "packages/schema/src/domains/webhook/WebhookSchemas.ts:WebhookBaseResponse",
        "src/internal/webhooks.ts:decodeWebhook",
        webhookEvidence,
        requiredResponse,
        unboundedResponse,
        responseProjection,
    ),
    rule(
        "Webhook.avatar",
        "response",
        "packages/schema/src/domains/webhook/WebhookSchemas.ts:WebhookBaseResponse.avatar",
        "src/internal/webhooks.ts:decodeWebhook",
        webhookEvidence,
        valueDefault("null", "A nullish or absent provider avatar projects to explicit null"),
        unboundedResponse,
        responseProjection,
    ),
    rule(
        "WebhookCredentials.id",
        "response",
        "packages/schema/src/domains/webhook/WebhookSchemas.ts:WebhookBaseResponse.id",
        "src/internal/webhooks.ts:credentials",
        webhookEvidence,
        requiredResponse,
        scalarLength,
        preserved("The created webhook's validated decimal ID is copied into the frozen credential capability"),
    ),
]

export const oauthUserFieldRules = defineFieldRules([
    ...oauthRequestRules,
    ...oauthResponseRules,
    ...userRequestRules,
    ...userResponseRules,
    ...userGatewayRules,
    ...webhookRequestRules,
    ...webhookResponseRules,
])

export const oauthUserLocalFieldExclusions = defineLocalFieldExclusions([
    {
        target: "DefaultOAuthOperationOptions.timeoutMs",
        direction: "request",
        rationale:
            "SDK-owned operation deadline spanning discovery, request work and awaited cleanup; no provider field exists",
        sdkOwner: "src/internal/oauth.ts:OAuthOwner.#run",
        executableEvidence: oauthEvidence,
    },
    {
        target: "DirectMessageLatestMessages.omittedChannelIds",
        direction: "response",
        rationale:
            "SDK-derived input-order difference between requested IDs and keys present in the provider response record",
        sdkOwner: "src/internal/users.ts:directMessageLatestMessages",
        executableEvidence: userEvidence,
    },
    {
        target: "CreatedWebhook.webhook",
        direction: "response",
        rationale: "SDK-only token-free wrapper property around fields already annotated on Webhook",
        sdkOwner: "src/internal/webhooks.ts:webhookCreate",
        executableEvidence: webhookEvidence,
    },
    {
        target: "CreatedWebhook.credentials",
        direction: "response",
        rationale: "SDK-only secret-bearing capability separated from the provider webhook response",
        sdkOwner: "src/internal/webhooks.ts:webhookCreate",
        executableEvidence: webhookEvidence,
    },
    {
        target: "WebhookCredentials.revealToken",
        direction: "response",
        rationale: "SDK-only accessor that prevents the provider token from appearing as an enumerable snapshot field",
        sdkOwner: "src/internal/webhooks.ts:credentials",
        executableEvidence: webhookEvidence,
    },
])
