import {
    defineFieldRules,
    defineLocalFieldExclusions,
    type FieldDirection,
    type FieldRuleAnnotation,
} from "./conformance-fields-registry.js"

const messageEvidence = ["tests/message-features.test.ts", "tests/messages.test.ts"] as const
const messageResponseEvidence = ["tests/message-fields.test.ts", "tests/message-events.test.ts"] as const
const embedEvidence = ["tests/embeds.test.ts", "tests/message-fields.test.ts"] as const
const attachmentEvidence = ["tests/attachments.test.ts", "tests/message-fields.test.ts"] as const
const reactionEvidence = ["tests/reactions.test.ts"] as const
const pinEvidence = ["tests/pins.test.ts"] as const
const cleanupEvidence = ["tests/message-cleanup.test.ts"] as const

const omitted = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "omitted", detail })
const noDefault = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "none", detail })
const providerDefault = (detail: string): FieldRuleAnnotation["default"] => ({ kind: "provider", detail })
const valueDefault = (value: string, detail: string): FieldRuleAnnotation["default"] => ({
    kind: "value",
    value,
    detail,
})
const notApplicableLength = (detail: string): FieldRuleAnnotation["length"] => ({
    kind: "not-applicable",
    detail,
})
const bounded = (
    unit: Extract<FieldRuleAnnotation["length"], { kind: "bounded" }>["unit"],
    minimum: number | undefined,
    maximum: number | undefined,
    detail: string,
): FieldRuleAnnotation["length"] => ({
    kind: "bounded",
    unit,
    ...(minimum === undefined ? {} : { minimum }),
    ...(maximum === undefined ? {} : { maximum }),
    detail,
})
const preserved = (detail: string): FieldRuleAnnotation["normalization"] => ({ kind: "preserved", detail })
const canonicalized = (detail: string): FieldRuleAnnotation["normalization"] => ({
    kind: "canonicalized",
    detail,
})
const providerView = (detail: string): FieldRuleAnnotation["normalization"] => ({
    kind: "provider-normalized-view",
    detail,
})

function rules(
    targets: readonly string[],
    direction: FieldDirection,
    providerOwner: FieldRuleAnnotation["providerOwner"],
    sdkOwner: FieldRuleAnnotation["sdkOwner"],
    defaultRule: FieldRuleAnnotation["default"],
    length: FieldRuleAnnotation["length"],
    normalization: FieldRuleAnnotation["normalization"],
    executableEvidence: FieldRuleAnnotation["executableEvidence"],
): readonly FieldRuleAnnotation[] {
    return targets.map((target) => ({
        target,
        direction,
        providerOwner,
        sdkOwner,
        default: defaultRule,
        length,
        normalization,
        executableEvidence,
    }))
}

const optionalRequest = omitted("An absent optional public property is not serialized")
const scalarLength = notApplicableLength("This field is not a variable-length collection or bounded request string")
const unboundedResponseLength = notApplicableLength(
    "Neither the pinned provider response schema nor the SDK projection declares a public response-length bound",
)
const responseProjection = providerView(
    "The SDK validates the provider value, renames its wire key when needed, and freezes the projected snapshot",
)
const optionalResponseProjection = providerView(
    "The SDK preserves an explicit null only where the public type permits it; otherwise nullish optional wire values are omitted",
)
const requiredResponse = noDefault(
    "A valid provider observation must supply this field; the SDK rejects absence rather than substituting a default",
)

const messageRequestRules = [
    ...rules(
        ["AllowedMentions.users", "AllowedMentions.roles"],
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:AllowedMentionsRequest",
        "src/internal/message.ts:encodeAllowedMentions",
        valueDefault("[]", "Omission serializes an empty ID array so the category cannot notify"),
        bounded("items", 0, 100, "Fluxer accepts at most 100 selected IDs per mention category"),
        preserved("The SDK snapshots IDs in caller order and serializes the same decimal strings"),
        messageEvidence,
    ),
    ...rules(
        ["AllowedMentions.everyone"],
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:AllowedMentionsRequest",
        "src/internal/message.ts:encodeAllowedMentions",
        valueDefault("false", "Omission serializes an empty parse list, disabling @everyone and @here notifications"),
        scalarLength,
        canonicalized("True becomes the provider parse token everyone; false becomes an empty parse list"),
        messageEvidence,
    ),
    ...rules(
        ["AllowedMentions.repliedUser"],
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:AllowedMentionsRequest",
        "src/internal/message.ts:encodeAllowedMentions",
        valueDefault("false", "Omission serializes replied_user false"),
        scalarLength,
        canonicalized("The public camelCase key is serialized as replied_user without changing the boolean"),
        messageEvidence,
    ),
    ...rules(
        ["MessageInput.content", "ReplyInput.content", "EditMessageInput.content"],
        "request",
        "fluxer_api/src/api/channel/services/message/MessageValidationService.ts:validateContentLength",
        "src/internal/message.ts:encodeBody",
        optionalRequest,
        bounded(
            "UTF-16-code-units",
            0,
            4000,
            "The pinned default bot/webhook limit is 4,000 JavaScript string length units; instance limit configuration can raise it and Fluxer enforces the effective value",
        ),
        preserved("Message content is serialized without trimming or rewriting"),
        messageEvidence,
    ),
    ...rules(
        ["MessageInput.embeds", "ReplyInput.embeds", "EditMessageInput.embeds"],
        "request",
        "fluxer_api/src/api/channel/services/message/MessageValidationService.ts:validateMessageContent",
        "src/internal/message.ts:encodeBody",
        optionalRequest,
        bounded(
            "items",
            0,
            10,
            "The pinned provider fallback is ten embeds per message; instance limit configuration can replace the effective maximum",
        ),
        canonicalized("Each embed is validated and projected to the provider wire shape in caller order"),
        embedEvidence,
    ),
    ...rules(
        ["MessageInput.attachments", "ReplyInput.attachments", "EditMessageInput.attachments"],
        "request",
        "fluxer_api/src/api/channel/services/message/MessageValidationService.ts:validateMessageContent",
        "src/internal/attachments.ts:encodeAttachments",
        optionalRequest,
        bounded(
            "items",
            0,
            10,
            "The pinned provider fallback is ten attachments per message; instance limit configuration can replace the effective maximum",
        ),
        canonicalized(
            "Local byte sources become provider attachment metadata and uploads; retained references keep caller order",
        ),
        attachmentEvidence,
    ),
    ...rules(
        ["MessageInput.flags", "ReplyInput.flags"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:MessageRequestSchema",
        "src/internal/message.ts:writableFlags",
        providerDefault("Omission uses Fluxer's zero default for a newly created message"),
        scalarLength,
        preserved("Accepted writable flag bits are serialized as the same integer"),
        messageEvidence,
    ),
    ...rules(
        ["EditMessageInput.flags"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:MessageRequestSchema",
        "src/internal/message.ts:writableFlags",
        optionalRequest,
        scalarLength,
        preserved("An explicit writable flag set is serialized unchanged; omission leaves existing flags unchanged"),
        messageEvidence,
    ),
    ...rules(
        ["MessageInput.nonce", "ReplyInput.nonce", "ForwardMessageInput.nonce"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:MessageNonceRequest",
        "src/internal/message.ts:encodeNonce",
        valueDefault("SDK-generated nonce", "Each send execution generates a nonce when the caller omits one"),
        bounded("UTF-16-code-units", 1, 32, "String nonces contain 1 through 32 JavaScript string length units"),
        canonicalized(
            "A nonnegative safe integer nonce is converted to its decimal string; string nonces are preserved",
        ),
        messageEvidence,
    ),
    ...rules(
        ["MessageInput.stickerIds", "ReplyInput.stickerIds"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:MessageRequestSchema",
        "src/internal/message.ts:encodeMessage",
        optionalRequest,
        bounded("items", 0, 3, "Fluxer accepts at most three sticker IDs"),
        preserved("The SDK snapshots decimal sticker IDs in caller order"),
        messageEvidence,
    ),
    ...rules(
        ["MessageInput.allowedMentions", "ReplyInput.allowedMentions", "EditMessageInput.allowedMentions"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:MessageRequestSchema",
        "src/internal/message.ts:encodeAllowedMentions",
        valueDefault("no notifications", "Omission serializes empty users, roles and parse plus replied_user false"),
        scalarLength,
        canonicalized("The SDK serializes a complete restrictive provider allowed_mentions object"),
        messageEvidence,
    ),
    ...rules(
        ["MessageInput.messageReference"],
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:MessageReferenceRequest",
        "src/internal/message.ts:encodeMessage",
        optionalRequest,
        scalarLength,
        canonicalized("The SDK renames id and channelId and supplies provider reference type 0"),
        messageEvidence,
    ),
    ...rules(
        ["ForwardMessageInput.source"],
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:MessageReferenceRequest",
        "src/internal/message.ts:encodeForward",
        noDefault("A forward source is required"),
        scalarLength,
        canonicalized("The source is serialized as message_id and channel_id with provider reference type 1"),
        messageEvidence,
    ),
    ...rules(
        ["ForwardMessageInput.attachmentIds", "ForwardMessageInput.embedIndices"],
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:MessageReferenceRequest",
        "src/internal/message.ts:encodeForward",
        optionalRequest,
        bounded("items", 0, 10, "Fluxer accepts at most ten selected attachment IDs or embed indices"),
        preserved("The SDK snapshots selector entries in caller order and renames only the wire key"),
        messageEvidence,
    ),
    ...rules(
        ["MessageReference.id", "MessageReference.channelId"],
        "request",
        "packages/schema/src/domains/message/SharedMessageSchemas.ts:MessageReferenceRequest",
        "src/internal/message.ts:snapshotReference",
        noDefault("Both address fields are required"),
        scalarLength,
        canonicalized("Decimal strings are preserved while public keys become message_id and channel_id"),
        messageEvidence,
    ),
    ...rules(
        ["MessageHistoryQuery.before", "MessageHistoryQuery.after", "MessageHistoryQuery.around"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:MessagesQuery",
        "src/internal/message.ts:encodeHistory",
        optionalRequest,
        scalarLength,
        preserved("The selected decimal cursor is serialized unchanged; the SDK rejects multiple cursor modes"),
        ["tests/message-history.test.ts"],
    ),
    ...rules(
        ["MessageHistoryQuery.limit"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:MessagesQuery",
        "src/internal/message.ts:encodeHistory",
        valueDefault("50", "The SDK serializes limit 50 when the query omits it"),
        bounded("items", 1, 100, "The integer is the maximum messages requested in one page"),
        preserved("The accepted integer is serialized in decimal form without changing its value"),
        ["tests/message-history.test.ts"],
    ),
] as const

const embedRequestRules = [
    ...rules(
        ["EmbedAuthorInput.url", "EmbedAuthorInput.iconUrl", "EmbedFooterInput.iconUrl", "EmbedInput.url"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:RichEmbedRequest",
        "src/internal/embeds.ts:projectInput",
        optionalRequest,
        bounded(
            "UTF-16-code-units",
            undefined,
            2048,
            "The SDK accepts only HTTP(S) URLs of at most 2,048 string length units",
        ),
        preserved("Accepted URLs are serialized unchanged under their provider wire keys"),
        embedEvidence,
    ),
    ...rules(
        ["EmbedMediaInput.url"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:RichEmbedMediaRequestShape",
        "src/internal/embeds.ts:attachmentUrl",
        noDefault("Media URL is required whenever the media object is supplied"),
        bounded(
            "UTF-16-code-units",
            1,
            2048,
            "HTTP(S) and attachment URLs contain 1 through 2,048 string length units",
        ),
        preserved("HTTP(S) URLs are unchanged; attachment URLs are accepted only for one matching new image upload"),
        embedEvidence,
    ),
    ...rules(
        ["EmbedFieldInput.inline"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:RichEmbedFieldRequest",
        "src/internal/embeds.ts:inputField.inline",
        providerDefault("The SDK omits the field and Fluxer supplies false"),
        scalarLength,
        preserved("An explicit boolean is serialized unchanged"),
        embedEvidence,
    ),
    ...rules(
        ["EmbedInput.author", "EmbedInput.footer", "EmbedInput.image", "EmbedInput.thumbnail"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:RichEmbedRequest",
        "src/internal/embeds.ts:inputEmbed",
        optionalRequest,
        scalarLength,
        canonicalized("The nested object is projected to its provider wire shape without mutating caller data"),
        embedEvidence,
    ),
    ...rules(
        ["EmbedInput.fields"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:RichEmbedRequest",
        "src/internal/embeds.ts:inputEmbed.fields",
        optionalRequest,
        bounded("items", 0, 25, "Fluxer accepts at most 25 rich-embed fields"),
        canonicalized("Fields are validated, projected and serialized in caller order"),
        embedEvidence,
    ),
    ...rules(
        ["EmbedInput.color"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:RichEmbedRequest",
        "src/internal/embeds.ts:inputEmbed.color",
        optionalRequest,
        scalarLength,
        preserved("The accepted integer from 0 through 16,777,215 is serialized unchanged"),
        embedEvidence,
    ),
    ...rules(
        ["EmbedInput.timestamp"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:RichEmbedRequest",
        "src/internal/embeds.ts:inputEmbed.timestamp",
        optionalRequest,
        scalarLength,
        preserved("The validated ISO 8601 timestamp with timezone is serialized unchanged"),
        embedEvidence,
    ),
] as const

const attachmentRequestRules = [
    ...rules(
        ["AttachmentInput.filename"],
        "request",
        "packages/schema/src/domains/message/AttachmentSchemas.ts:ClientAttachmentRequest",
        "src/internal/attachments.ts:filename",
        noDefault("Every new upload requires a display filename"),
        bounded(
            "UTF-16-code-units",
            1,
            255,
            "The SDK accepts 1 through 255 string length units and rejects controls and path separators",
        ),
        preserved("The accepted display filename is sent unchanged; Fluxer may normalize its upload view"),
        attachmentEvidence,
    ),
    ...rules(
        ["AttachmentInput.contentType"],
        "request",
        "packages/schema/src/domains/message/AttachmentSchemas.ts:ClientAttachmentRequest",
        "src/internal/attachments.ts:contentType",
        valueDefault("application/octet-stream", "The SDK uses this MIME type when the caller omits the hint"),
        bounded("bytes", 1, 255, "Only printable ASCII is accepted, so the length is also the encoded byte count"),
        preserved("An explicit printable-ASCII MIME hint is sent unchanged; Fluxer's upload plan may override it"),
        attachmentEvidence,
    ),
    ...rules(
        ["AttachmentInput.title", "AttachmentReference.title"],
        "request",
        "packages/schema/src/domains/message/AttachmentSchemas.ts:ClientAttachmentBase",
        "src/internal/attachments.ts:encodeAttachments",
        optionalRequest,
        bounded("UTF-16-code-units", 1, 1024, "Non-null titles use the provider-normalized validation view"),
        providerView(
            "Validation removes U+000C and U+202E and trims outer whitespace; serialization preserves the original string",
        ),
        attachmentEvidence,
    ),
    ...rules(
        ["AttachmentInput.description", "AttachmentReference.description"],
        "request",
        "packages/schema/src/domains/message/AttachmentSchemas.ts:ClientAttachmentBase",
        "src/internal/attachments.ts:encodeAttachments",
        optionalRequest,
        bounded("UTF-16-code-units", 1, 4096, "Non-null descriptions use the provider-normalized validation view"),
        providerView(
            "Validation removes U+000C and U+202E and trims outer whitespace; serialization preserves the original string",
        ),
        attachmentEvidence,
    ),
    ...rules(
        ["AttachmentInput.spoiler"],
        "request",
        "packages/schema/src/domains/message/AttachmentSchemas.ts:ClientAttachmentBase",
        "src/internal/attachments.ts:metadata",
        valueDefault("false", "Omission leaves the provider attachment flags at zero"),
        scalarLength,
        canonicalized("True is encoded as provider attachment flag bit 1 << 3; false as zero"),
        attachmentEvidence,
    ),
    ...rules(
        ["AttachmentInput.size"],
        "request",
        "packages/constants/src/LimitConstants.ts:ATTACHMENT_MAX_SIZE_BOT",
        "src/internal/attachments.ts:encodeAttachments",
        noDefault("A stream upload requires its exact byte count; byte and file inputs derive it from their source"),
        bounded("bytes", 0, 52_428_800, "The exact stream or source byte count is bounded to 50 MiB"),
        canonicalized("The SDK serializes the exact validated count as provider file_size metadata"),
        attachmentEvidence,
    ),
    ...rules(
        ["AttachmentReference.id"],
        "request",
        "packages/schema/src/domains/message/AttachmentSchemas.ts:ClientAttachmentReferenceRequest",
        "src/internal/attachments.ts:encodeAttachments",
        noDefault("A retained attachment reference requires its existing decimal ID"),
        scalarLength,
        preserved("The decimal attachment ID is serialized unchanged and must be unique in the replacement list"),
        attachmentEvidence,
    ),
    ...rules(
        [
            "Attachment.contentHash",
            "Attachment.contentType",
            "Attachment.description",
            "Attachment.expired",
            "Attachment.expiresAt",
            "Attachment.height",
            "Attachment.nsfw",
            "Attachment.placeholder",
            "Attachment.proxyUrl",
            "Attachment.title",
            "Attachment.url",
            "Attachment.waveform",
            "Attachment.width",
        ],
        "request",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageAttachmentResponse",
        "src/internal/attachments.ts:decodeAttachments",
        omitted("The accepted provider-originated Attachment snapshot may omit this optional metadata member"),
        scalarLength,
        preserved(
            "Provider metadata is already projected; download operations snapshot the selected signed URL and limits",
        ),
        attachmentEvidence,
    ),
    ...rules(
        ["Attachment.id", "Attachment.filename", "Attachment.flags"],
        "request",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageAttachmentResponse",
        "src/internal/attachments.ts:decodeAttachments",
        noDefault("The accepted provider-originated Attachment snapshot requires this field"),
        scalarLength,
        preserved("Provider metadata is already projected and the attachment media operation snapshots it unchanged"),
        attachmentEvidence,
    ),
    ...rules(
        ["Attachment.size"],
        "request",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageAttachmentResponse",
        "src/internal/attachments.ts:decodeAttachments",
        noDefault("The accepted provider-originated Attachment snapshot requires its byte count"),
        bounded(
            "bytes",
            0,
            Number.MAX_SAFE_INTEGER,
            "The accepted provider snapshot uses a nonnegative safe-integer byte count",
        ),
        preserved("The already projected byte count is retained while the operation snapshots its own download limit"),
        attachmentEvidence,
    ),
    ...rules(
        ["Attachment.duration"],
        "request",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageAttachmentResponse",
        "src/internal/attachments.ts:decodeAttachments",
        omitted("The accepted provider-originated Attachment snapshot may omit duration"),
        bounded(
            "seconds",
            -2_147_483_648,
            2_147_483_647,
            "The accepted provider snapshot uses a signed-32-bit duration",
        ),
        preserved("The already projected duration is not rewritten by attachment media operations"),
        attachmentEvidence,
    ),
] as const

const paginationRequestRules = [
    ...rules(
        ["ReactionUsersQuery.after"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:ReactionUsersQuerySchema",
        "src/internal/reactions.ts:encodeReactionUsersQuery",
        optionalRequest,
        scalarLength,
        preserved("The decimal exclusive cursor is serialized unchanged"),
        reactionEvidence,
    ),
    ...rules(
        ["ReactionUsersQuery.limit"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:ReactionUsersQuerySchema",
        "src/internal/reactions.ts:encodeReactionUsersQuery",
        valueDefault("25", "The SDK serializes limit 25 when omitted"),
        bounded("items", 1, 100, "The integer bounds one returned user page"),
        preserved("The accepted integer is serialized in decimal form without changing its value"),
        reactionEvidence,
    ),
    ...rules(
        ["MessagePinsQuery.before"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:ChannelPinsQuerySchema",
        "src/internal/pins.ts:encodePinsQuery",
        providerDefault("Omission lets Fluxer select its current-time starting point"),
        scalarLength,
        preserved("The validated ISO 8601 timestamp with timezone is serialized unchanged"),
        pinEvidence,
    ),
    ...rules(
        ["MessagePinsQuery.limit"],
        "request",
        "packages/schema/src/domains/message/MessageRequestSchemas.ts:ChannelPinsQuerySchema",
        "src/internal/pins.ts:encodePinsQuery",
        valueDefault("50", "The SDK serializes limit 50 when omitted"),
        bounded("items", 1, 50, "The integer bounds one returned pin page"),
        preserved("The accepted integer is serialized in decimal form without changing its value"),
        pinEvidence,
    ),
] as const

const reactionInputRequestRules = [
    ...rules(
        ["ReactionEmojiInput.name"],
        "request",
        "fluxer_api/src/api/channel/services/interaction/MessageReactionService.ts:parseEmojiWithoutValidation",
        "src/internal/reactions.ts:resolveReactionEmoji",
        omitted(
            "The field is absent when the union input uses a Unicode or custom-markup string; object inputs require it",
        ),
        bounded(
            "UTF-16-code-units",
            1,
            128,
            "Unicode names use 1 through 128 units; custom object names have the stricter 1 through 32 ASCII-character bound",
        ),
        canonicalized(
            "The SDK percent-encodes Unicode text or combines a custom name and decimal ID into the route segment",
        ),
        reactionEvidence,
    ),
    ...rules(
        ["ReactionEmojiInput.id"],
        "request",
        "fluxer_api/src/api/channel/services/interaction/MessageReactionService.ts:parseEmojiWithoutValidation",
        "src/internal/reactions.ts:resolveReactionEmoji",
        omitted("Omission selects a Unicode emoji; a custom object requires a decimal ID"),
        notApplicableLength("The value is a decimal identifier and neither owner publishes a digit-count bound"),
        canonicalized(
            "The SDK combines the decimal ID with the validated custom name and percent-encodes the route segment",
        ),
        reactionEvidence,
    ),
    ...rules(
        ["ReactionEmojiInput.animated"],
        "request",
        "fluxer_api/src/api/channel/services/interaction/MessageReactionService.ts:parseEmojiWithoutValidation",
        "src/internal/reactions.ts:resolveReactionEmoji",
        omitted("Omission is accepted; the field is valid only beside a custom emoji ID"),
        scalarLength,
        canonicalized(
            "The SDK validates this metadata but the provider route identity contains only the custom name and ID",
        ),
        reactionEvidence,
    ),
    ...rules(
        ["ReactionEmojiInput.guildId"],
        "request",
        "fluxer_api/src/api/channel/services/interaction/MessageReactionService.ts:parseEmojiWithoutValidation",
        "src/internal/reactions.ts:resolveReactionEmoji",
        omitted(
            "Omission selects the ordinary reaction input form; reusable guild-emoji snapshots supply this decimal ID",
        ),
        notApplicableLength("The value is a decimal identifier and neither owner publishes a digit-count bound"),
        canonicalized(
            "The SDK validates guildId as snapshot provenance metadata but sends only the custom emoji name and ID in the provider route",
        ),
        reactionEvidence,
    ),
] as const

const optionalMessageResponseTargets = [
    "Message.createdAt",
    "Message.editedAt",
    "Message.flags",
    "Message.mentionChannels",
    "Message.mentionRoleIds",
    "Message.mentionedEveryone",
    "Message.mentions",
    "Message.messageReference",
    "Message.messageSnapshots",
    "Message.nonce",
    "Message.pinned",
    "Message.reactions",
    "Message.referencedMessage",
    "Message.referencedUsers",
    "Message.type",
    "Message.webhookId",
    "MessageContextReference.guildId",
    "MessageContextReference.type",
    "MessageReactionEmoji.animated",
    "MessageReactionEmoji.id",
    "MessageReactionSummary.me",
    "MessageSnapshot.attachments",
    "MessageSnapshot.content",
    "MessageSnapshot.editedAt",
    "MessageSnapshot.embeds",
    "MessageSnapshot.mentionChannels",
    "MessageSnapshot.mentionRoleIds",
    "MessageSnapshot.mentionUserIds",
    "MessageSnapshot.stickers",
    "ReferencedMessage.createdAt",
    "ReferencedMessage.editedAt",
    "ReferencedMessage.flags",
    "ReferencedMessage.mentionChannels",
    "ReferencedMessage.mentionRoleIds",
    "ReferencedMessage.mentionedEveryone",
    "ReferencedMessage.mentions",
    "ReferencedMessage.messageReference",
    "ReferencedMessage.messageSnapshots",
    "ReferencedMessage.nonce",
    "ReferencedMessage.pinned",
    "ReferencedMessage.reactions",
    "ReferencedMessage.referencedUsers",
    "ReferencedMessage.type",
    "ReferencedMessage.webhookId",
] as const

const requiredNestedMessageResponseTargets = [
    "MessageChannelMention.id",
    "MessageChannelMention.name",
    "MessageChannelMention.type",
    "MessageContextReference.channelId",
    "MessageContextReference.id",
    "MessageReactionEmoji.name",
    "MessageReactionSummary.count",
    "MessageReactionSummary.emoji",
    "MessageReference.channelId",
    "MessageReference.id",
    "MessageSnapshot.createdAt",
    "MessageSnapshot.flags",
    "MessageSnapshot.type",
    "MessageSticker.animated",
    "MessageSticker.id",
    "MessageSticker.name",
] as const

const optionalMessageDeletionGatewayTargets = [
    "MessageBulkDeletion.guildId",
    "MessageDeletion.authorId",
    "MessageDeletion.content",
    "MessageDeletion.guildId",
] as const

const requiredMessageDeletionGatewayTargets = [
    "MessageBulkDeletion.channelId",
    "MessageDeletion.channelId",
    "MessageDeletion.id",
] as const

const messageReactionEventGatewayTargets = [
    "MessageReaction.channelId",
    "MessageReaction.id",
    "MessageReactionEmojiRemoval.channelId",
    "MessageReactionEmojiRemoval.id",
    "ReactionTarget.channelId",
    "ReactionTarget.id",
] as const

const messageUserResponseTargets = [
    "MessageUser.avatar",
    "MessageUser.avatarColor",
    "MessageUser.discriminator",
    "MessageUser.displayName",
    "MessageUser.flags",
    "MessageUser.isSystem",
    "MessageUser.mentionFlags",
] as const

const messageResponseRules = [
    ...rules(
        [
            "Message.author",
            "Message.channelId",
            "Message.content",
            "Message.id",
            "ReferencedMessage.author",
            "ReferencedMessage.channelId",
            "ReferencedMessage.content",
            "ReferencedMessage.id",
        ],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageResponseSchema",
        "src/internal/message.ts:decodeMessageValue",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        messageResponseEvidence,
    ),
    ...rules(
        optionalMessageResponseTargets,
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageResponseSchema",
        "src/internal/message.ts:decodeMessageValue",
        omitted("The SDK preserves absence for this optional provider response field"),
        unboundedResponseLength,
        optionalResponseProjection,
        messageResponseEvidence,
    ),
    ...rules(
        requiredNestedMessageResponseTargets,
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageResponseSchema",
        "src/internal/message.ts:decodeMessageValue",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        messageResponseEvidence,
    ),
    ...rules(
        [
            "Message.attachments",
            "Message.embeds",
            "Message.stickers",
            "ReferencedMessage.attachments",
            "ReferencedMessage.embeds",
            "ReferencedMessage.stickers",
        ],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageResponseSchema",
        "src/internal/message.ts:decodeMessageValue",
        valueDefault("[]", "A nullish provider collection is projected as an empty frozen array"),
        unboundedResponseLength,
        canonicalized(
            "Null, absence and an empty provider array share the public empty-array view for this required collection",
        ),
        messageResponseEvidence,
    ),
    ...rules(
        ["Message.guildId", "ReferencedMessage.guildId"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:Message",
        "src/internal/message.ts:decodeMessageValue",
        omitted("The SDK preserves absence for this optional provider response field"),
        unboundedResponseLength,
        preserved(
            "The upstream Message interface permits guild_id; the SDK omits it when absent and preserves a decimal value",
        ),
        messageResponseEvidence,
    ),
    ...rules(
        ["Message.nsfwEmojiIds", "ReferencedMessage.nsfwEmojiIds"],
        "response",
        "fluxer_api/src/api/channel/services/message/MessageResponseDataService.ts:MessageResponseDataService",
        "src/internal/message.ts:decodeIdentifiers",
        omitted(
            "This supported optional SDK decoder-compatibility field is absent unless the response service supplies nsfw_emojis",
        ),
        unboundedResponseLength,
        providerView(
            "The SDK freezes supplied decimal IDs and omits null or absence; the contextual response-service owner is not verification of a provider field contract because the pinned TypeScript response schema omits nsfw_emojis",
        ),
        messageResponseEvidence,
    ),
    ...rules(
        optionalMessageDeletionGatewayTargets,
        "gateway",
        "fluxer_api/src/api/channel/services/message/MessageDispatchService.ts:dispatchMessageDelete",
        "src/internal/message.ts:decodeDeletion",
        omitted("The gateway decoder preserves absence for this optional event field"),
        unboundedResponseLength,
        optionalResponseProjection,
        messageResponseEvidence,
    ),
    ...rules(
        requiredMessageDeletionGatewayTargets,
        "gateway",
        "fluxer_api/src/api/channel/services/message/MessageDispatchService.ts:dispatchMessageDelete",
        "src/internal/message.ts:decodeDeletion",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        messageResponseEvidence,
    ),
    ...rules(
        ["MessageBulkDeletion.ids"],
        "gateway",
        "fluxer_api/src/api/channel/services/message/MessageDispatchService.ts:dispatchMessageDeleteBulk",
        "src/internal/message.ts:decodeBulkDeletion",
        requiredResponse,
        bounded(
            "items",
            1,
            100,
            "Fluxer's bulk-delete operation accepts at most 100 message IDs per event-producing request",
        ),
        preserved("The SDK freezes decimal IDs in provider order"),
        messageResponseEvidence,
    ),
    ...rules(
        messageReactionEventGatewayTargets,
        "gateway",
        "fluxer_api/src/api/channel/services/interaction/MessageReactionService.ts:dispatchMessageReactionAdd",
        "src/internal/reactions.ts:decodeReaction",
        requiredResponse,
        unboundedResponseLength,
        optionalResponseProjection,
        ["tests/reactions.test.ts"],
    ),
    ...rules(
        ["MessageUser.id", "MessageUser.username"],
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserPartialResponse",
        "src/internal/message.ts:decodeMessageUser",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        messageResponseEvidence,
    ),
    ...rules(
        messageUserResponseTargets,
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserPartialResponse",
        "src/internal/message.ts:decodeMessageUser",
        omitted("The SDK preserves absence for this optional provider response field"),
        unboundedResponseLength,
        optionalResponseProjection,
        messageResponseEvidence,
    ),
    ...rules(
        ["MessageUser.isBot"],
        "response",
        "packages/schema/src/domains/user/UserResponseSchemas.ts:UserPartialResponse",
        "src/internal/message.ts:decodeMessageUser",
        valueDefault("false", "The SDK projects a missing provider bot marker as false"),
        unboundedResponseLength,
        responseProjection,
        messageResponseEvidence,
    ),
] as const

const embedResponseTargets = [
    "Embed.audio",
    "Embed.author",
    "Embed.color",
    "Embed.description",
    "Embed.fields",
    "Embed.footer",
    "Embed.html",
    "Embed.htmlHeight",
    "Embed.htmlWidth",
    "Embed.image",
    "Embed.nsfw",
    "Embed.provider",
    "Embed.thumbnail",
    "Embed.timestamp",
    "Embed.title",
    "Embed.url",
    "Embed.video",
    "EmbedAuthor.iconUrl",
    "EmbedAuthor.proxyIconUrl",
    "EmbedAuthor.url",
    "EmbedChild.audio",
    "EmbedChild.author",
    "EmbedChild.color",
    "EmbedChild.description",
    "EmbedChild.fields",
    "EmbedChild.footer",
    "EmbedChild.html",
    "EmbedChild.htmlHeight",
    "EmbedChild.htmlWidth",
    "EmbedChild.image",
    "EmbedChild.nsfw",
    "EmbedChild.provider",
    "EmbedChild.thumbnail",
    "EmbedChild.timestamp",
    "EmbedChild.title",
    "EmbedChild.url",
    "EmbedChild.video",
    "EmbedFooter.iconUrl",
    "EmbedFooter.proxyIconUrl",
    "EmbedMedia.contentHash",
    "EmbedMedia.contentType",
    "EmbedMedia.description",
    "EmbedMedia.height",
    "EmbedMedia.placeholder",
    "EmbedMedia.proxyUrl",
    "EmbedMedia.width",
] as const

const requiredEmbedResponseTargets = [
    "Embed.type",
    "EmbedAuthor.name",
    "EmbedChild.type",
    "EmbedField.inline",
    "EmbedField.name",
    "EmbedField.value",
    "EmbedFooter.text",
    "EmbedMedia.flags",
    "EmbedMedia.url",
] as const

const embedResponseRules = [
    ...rules(
        embedResponseTargets,
        "response",
        "packages/schema/src/domains/message/EmbedSchemas.ts:MessageEmbedResponse",
        "src/internal/embeds.ts:decodeEmbeds",
        omitted("The embed decoder preserves absence for this optional provider response field"),
        unboundedResponseLength,
        optionalResponseProjection,
        embedEvidence,
    ),
    ...rules(
        requiredEmbedResponseTargets,
        "response",
        "packages/schema/src/domains/message/EmbedSchemas.ts:MessageEmbedResponse",
        "src/internal/embeds.ts:decodeEmbeds",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        embedEvidence,
    ),
] as const

const boundedEmbedResponseRules = [
    ...rules(
        ["Embed.children"],
        "response",
        "packages/schema/src/domains/message/EmbedSchemas.ts:MessageEmbedResponse",
        "src/internal/embeds.ts:outputEmbed.children",
        omitted("The embed decoder preserves absence for the optional child collection"),
        bounded("items", 0, 1, "Both the provider schema and SDK decoder allow at most one nested child embed"),
        canonicalized("The optional child collection retains provider order and is frozen"),
        embedEvidence,
    ),
    ...rules(
        ["EmbedMedia.duration"],
        "response",
        "packages/schema/src/domains/message/EmbedSchemas.ts:EmbedMediaResponse",
        "src/internal/embeds.ts:outputMedia.duration",
        omitted("The embed decoder preserves absence for optional media duration"),
        bounded("seconds", 0, 2_147_483_647, "The SDK accepts a nonnegative signed-32-bit media duration"),
        optionalResponseProjection,
        embedEvidence,
    ),
] as const

const attachmentResponseTargets = [
    "Attachment.contentHash",
    "Attachment.contentType",
    "Attachment.description",
    "Attachment.expired",
    "Attachment.expiresAt",
    "Attachment.height",
    "Attachment.nsfw",
    "Attachment.placeholder",
    "Attachment.proxyUrl",
    "Attachment.title",
    "Attachment.url",
    "Attachment.waveform",
    "Attachment.width",
] as const

const attachmentResponseRules = [
    ...rules(
        ["Attachment.id", "Attachment.filename", "Attachment.flags"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageAttachmentResponse",
        "src/internal/attachments.ts:decodeAttachments",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        attachmentEvidence,
    ),
    ...rules(
        attachmentResponseTargets,
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageAttachmentResponse",
        "src/internal/attachments.ts:decodeAttachments",
        omitted("The attachment decoder preserves absence for this optional provider response field"),
        unboundedResponseLength,
        optionalResponseProjection,
        attachmentEvidence,
    ),
    ...rules(
        ["Attachment.size"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageAttachmentResponse",
        "src/internal/attachments.ts:decodeAttachments",
        requiredResponse,
        bounded("bytes", 0, Number.MAX_SAFE_INTEGER, "Fluxer and the SDK accept a nonnegative safe-integer byte count"),
        responseProjection,
        attachmentEvidence,
    ),
    ...rules(
        ["Attachment.duration"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:MessageAttachmentResponse",
        "src/internal/attachments.ts:decodeAttachments",
        omitted("The attachment decoder preserves absence for optional media duration"),
        bounded(
            "seconds",
            -2_147_483_648,
            2_147_483_647,
            "The pinned schema and SDK decoder accept a signed-32-bit duration",
        ),
        optionalResponseProjection,
        attachmentEvidence,
    ),
    ...rules(
        ["RefreshedAttachmentUrl.original", "RefreshedAttachmentUrl.refreshed"],
        "response",
        "packages/schema/src/domains/message/AttachmentSchemas.ts:RefreshedAttachmentUrl",
        "src/internal/attachment-refresh.ts:decodeRefreshResponse",
        requiredResponse,
        unboundedResponseLength,
        preserved("The ordered strings are returned exactly as supplied by Fluxer's refresh response"),
        ["tests/attachment-refresh.test.ts"],
    ),
] as const

const reactionResponseRules = [
    ...rules(
        [
            "MessageReaction.guildId",
            "MessageReactionEmojiRemoval.guildId",
            "ReactionEmoji.animated",
            "ReactionEmoji.id",
            "ReactionTarget.guildId",
        ],
        "gateway",
        "fluxer_api/src/api/channel/services/interaction/MessageReactionService.ts:dispatchMessageReactionAdd",
        "src/internal/reactions.ts:decodeReaction",
        omitted("The gateway decoder preserves absence for this optional reaction event field"),
        unboundedResponseLength,
        optionalResponseProjection,
        reactionEvidence,
    ),
    ...rules(
        ["MessageReaction.emoji", "MessageReaction.userId", "MessageReactionEmojiRemoval.emoji"],
        "gateway",
        "fluxer_api/src/api/channel/services/interaction/MessageReactionService.ts:dispatchMessageReactionAdd",
        "src/internal/reactions.ts:decodeReaction",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        reactionEvidence,
    ),
    ...rules(
        ["ReactionEmoji.name"],
        "gateway",
        "fluxer_api/src/api/channel/services/interaction/MessageReactionService.ts:dispatchMessageReactionAdd",
        "src/internal/reactions.ts:emoji",
        requiredResponse,
        bounded("UTF-16-code-units", 1, 128, "The SDK bounds received event emoji names before projection"),
        preserved("The accepted literal Unicode text or custom emoji name is retained unchanged"),
        reactionEvidence,
    ),
    ...rules(
        ["MessageReactionBatch.guildId"],
        "gateway",
        "fluxer_app/src/features/messaging/events/MessageReactionAddMany.ts:MessageReactionAddManyPayload",
        "src/internal/reactions.ts:decodeReaction",
        omitted("The gateway decoder preserves absence for optional guild context"),
        unboundedResponseLength,
        optionalResponseProjection,
        reactionEvidence,
    ),
    ...rules(
        ["MessageReactionBatch.channelId", "MessageReactionBatch.id"],
        "gateway",
        "fluxer_app/src/features/messaging/events/MessageReactionAddMany.ts:MessageReactionAddManyPayload",
        "src/internal/reactions.ts:decodeReaction",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        reactionEvidence,
    ),
    ...rules(
        ["MessageReactionBatch.reactions"],
        "gateway",
        "fluxer_app/src/features/messaging/events/MessageReactionAddMany.ts:MessageReactionAddManyPayload",
        "src/internal/reactions.ts:decodeReaction",
        requiredResponse,
        bounded("items", 1, 512, "The SDK rejects empty or over-capacity gateway reaction batches"),
        canonicalized("Entries retain provider order and are frozen after their wire keys are projected"),
        reactionEvidence,
    ),
    ...rules(
        ["ReactionUser.id", "ReactionUser.username"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:ReactionUsersPageResponse",
        "src/internal/reactions.ts:decodeReactionUsersPage",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        reactionEvidence,
    ),
    ...rules(
        ["ReactionUser.isBot"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:ReactionUsersPageResponse",
        "src/internal/reactions.ts:decodeReactionUsersPage",
        valueDefault("false", "The SDK maps an absent provider bot marker to false"),
        unboundedResponseLength,
        responseProjection,
        reactionEvidence,
    ),
    ...rules(
        ["ReactionUsersPage.items"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:ReactionUsersPageResponse",
        "src/internal/reactions.ts:decodeReactionUsersPage",
        requiredResponse,
        bounded("items", 0, 100, "A page cannot exceed the requested limit, whose provider maximum is 100"),
        canonicalized("Users retain provider order; the SDK additionally verifies strictly increasing IDs"),
        reactionEvidence,
    ),
    ...rules(
        ["ReactionUsersPage.hasMore", "ReactionUsersPage.nextAfter"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:ReactionUsersPageResponse",
        "src/internal/reactions.ts:decodeReactionUsersPage",
        requiredResponse,
        unboundedResponseLength,
        canonicalized("When more items exist, nextAfter must equal the last returned ID; otherwise it must be null"),
        reactionEvidence,
    ),
] as const

const pinResponseRules = [
    ...rules(
        ["MessagePin.message", "MessagePin.pinnedAt"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:ChannelPinResponse",
        "src/internal/pins.ts:decodePinsPage",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        pinEvidence,
    ),
    ...rules(
        ["MessagePinsPage.items"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:ChannelPinsResponse",
        "src/internal/pins.ts:decodePinsPage",
        requiredResponse,
        bounded("items", 0, 50, "A page cannot exceed the requested limit, whose provider maximum is 50"),
        canonicalized(
            "Pins retain newest-first provider order; the SDK rejects duplicate IDs and increasing timestamps",
        ),
        pinEvidence,
    ),
    ...rules(
        ["MessagePinsPage.hasMore"],
        "response",
        "packages/schema/src/domains/message/MessageResponseSchemas.ts:ChannelPinsResponse",
        "src/internal/pins.ts:decodePinsPage",
        requiredResponse,
        unboundedResponseLength,
        preserved("The provider boolean is retained after consistency validation"),
        pinEvidence,
    ),
    ...rules(
        ["MessagePinsPage.nextBefore"],
        "response",
        "fluxer_api/src/api/channel/services/interaction/MessagePinService.ts:getChannelPins",
        "src/internal/pins.ts:decodePinsPage",
        valueDefault("null", "The SDK returns null when Fluxer reports no further page"),
        unboundedResponseLength,
        canonicalized("When more pins exist, the SDK derives the cursor from the last returned pinnedAt value"),
        pinEvidence,
    ),
    ...rules(
        ["ChannelPinsUpdate.guildId"],
        "gateway",
        "fluxer_api/src/api/channel/services/interaction/MessagePinService.ts:dispatchChannelPinsUpdate",
        "src/internal/pins.ts:decodePinsUpdate",
        omitted("The gateway decoder preserves absence for optional guild context"),
        unboundedResponseLength,
        optionalResponseProjection,
        pinEvidence,
    ),
    ...rules(
        ["ChannelPinsUpdate.channelId", "ChannelPinsUpdate.lastPinTimestamp"],
        "gateway",
        "fluxer_api/src/api/channel/services/interaction/MessagePinService.ts:dispatchChannelPinsUpdate",
        "src/internal/pins.ts:decodePinsUpdate",
        requiredResponse,
        unboundedResponseLength,
        responseProjection,
        pinEvidence,
    ),
] as const

/** Complete direction-qualified field contracts for message, embed, attachment, reaction and pin provider data. */
export const messageFieldRules = defineFieldRules([
    ...messageRequestRules,
    ...embedRequestRules,
    ...attachmentRequestRules,
    ...paginationRequestRules,
    ...reactionInputRequestRules,
    ...messageResponseRules,
    ...embedResponseRules,
    ...boundedEmbedResponseRules,
    ...attachmentResponseRules,
    ...reactionResponseRules,
    ...pinResponseRules,
])

/** SDK execution, source and forbidden-union fields that have no provider field contract of their own. */
export const messageLocalFieldExclusions = defineLocalFieldExclusions([
    ...(
        [
            ["DefaultAttachmentRefreshOptions.timeoutMs", "tests/attachment-refresh.test.ts"],
            ["DefaultBotApplicationOperationOptions.timeoutMs", "tests/applications.test.ts"],
            ["DefaultMessageCleanupOptions.timeoutMs", "tests/message-cleanup.test.ts"],
            ["DefaultMessageOperationOptions.timeoutMs", "tests/messages.test.ts"],
            ["DefaultMessageSearchOptions.timeoutMs", "tests/message-search.test.ts"],
            ["DefaultSendOptions.timeoutMs", "tests/messages.test.ts"],
            ["DefaultUserOperationOptions.timeoutMs", "tests/users.test.ts"],
            ["DefaultWebhookOperationOptions.timeoutMs", "tests/webhooks.test.ts"],
        ] as const
    ).map(([target, evidence]) => ({
        target,
        direction: "request" as const,
        rationale: "SDK-owned operation deadline inherited from MessageOperationOptions, not a provider request field",
        sdkOwner: "src/messages.ts:MessageOperationOptions" as const,
        executableEvidence: [evidence],
    })),
    ...[
        "DefaultAttachmentDownloadOptions.maxBytes",
        "DefaultAttachmentDownloadOptions.timeoutMs",
        "DefaultAttachmentStreamOptions.maxBytes",
        "DefaultAttachmentStreamOptions.timeoutMs",
    ].map((target) => ({
        target,
        direction: "request" as const,
        rationale: "SDK-owned media output or deadline bound applied around the GET, not serialized to Fluxer",
        sdkOwner: "src/attachments.ts:AttachmentDownloadOptions" as const,
        executableEvidence: attachmentEvidence,
    })),
    ...[
        "AttachmentFileSource.size",
        "AttachmentFileSource.slice",
        "AttachmentFileSource.stream",
        "AttachmentInput.data",
        "AttachmentInput.file",
        "AttachmentInput.stream",
        "AttachmentStreamReader.cancel",
        "AttachmentStreamReader.read",
        "AttachmentStreamReader.releaseLock",
        "AttachmentStreamReaderOptions.mode",
        "AttachmentStreamSource.getReader",
    ].map((target) => ({
        target,
        direction: "request" as const,
        rationale:
            "Local byte-source and reader protocol consumed by the SDK; only derived bytes and metadata cross the provider boundary",
        sdkOwner: "src/attachments.ts:attachment source types" as const,
        executableEvidence: attachmentEvidence,
    })),
    ...[
        "AttachmentInput.id",
        "AttachmentReference.contentType",
        "AttachmentReference.data",
        "AttachmentReference.file",
        "AttachmentReference.filename",
        "AttachmentReference.size",
        "AttachmentReference.spoiler",
        "AttachmentReference.stream",
    ].map((target) => ({
        target,
        direction: "request" as const,
        rationale:
            "Type-level never member that prevents mixing new-upload and retained-attachment forms; no supported value is serialized",
        sdkOwner: "src/attachments.ts:AttachmentInput" as const,
        executableEvidence: attachmentEvidence,
    })),
    ...["DefaultMessageCleanupOptions.onProgress"].map((target) => ({
        target,
        direction: "request" as const,
        rationale:
            "SDK-owned synchronous progress observer invoked around batch submissions; callbacks are never serialized to Fluxer",
        sdkOwner: "src/message-cleanup.ts:MessageCleanupOptions" as const,
        executableEvidence: cleanupEvidence,
    })),
    ...[
        "MessageCleanupPlan.channelId",
        "MessageCleanupPlan.scannedCount",
        "MessageCleanupPlan.selectedMessages",
        "MessageCleanupPlan.stopReason",
    ].map((target) => ({
        target,
        direction: "request" as const,
        rationale:
            "SDK-owned, provenance-checked preview plan; cleanup derives bounded delete requests from it rather than serializing this public object",
        sdkOwner: "src/message-cleanup.ts:MessageCleanupPlan" as const,
        executableEvidence: cleanupEvidence,
    })),
    ...["MessageCleanupBatch.batchIndex", "MessageCleanupBatch.messageIds"].map((target) => ({
        target,
        direction: "response" as const,
        rationale:
            "SDK-owned cleanup progress and report projection derived from submitted batches, not a provider response field",
        sdkOwner: "src/message-cleanup.ts:MessageCleanupBatch" as const,
        executableEvidence: cleanupEvidence,
    })),
    ...[
        "MessageCleanupReport.channelId",
        "MessageCleanupReport.scannedCount",
        "MessageCleanupReport.selectedMessageIds",
        "MessageCleanupReport.submittedBatches",
    ].map((target) => ({
        target,
        direction: "response" as const,
        rationale:
            "SDK-owned cleanup execution report assembled from the validated plan and successful submissions, not decoded from a provider response body",
        sdkOwner: "src/message-cleanup.ts:MessageCleanupReport" as const,
        executableEvidence: cleanupEvidence,
    })),
])
