import { test, expect } from "@playwright/test"
import AxeBuilder from "@axe-core/playwright"

for (const width of [390, 1440, 1920]) {
    test(`Readable guide and reference at ${width}px`, async ({ page }, info) => {
        await page.setViewportSize({ width, height: 900 })
        const errors: string[] = []
        page.on("pageerror", (error) => errors.push(error.message))
        page.on("response", (response) => {
            if (response.status() >= 400) errors.push(`${response.status()} ${response.url()}`)
        })
        await page.goto("/docs/dev/quick-start/")
        await expect(page.locator('astro-island[component-export="Docs"]')).not.toHaveAttribute("ssr")
        await page.evaluate(() => document.fonts.ready)
        await expect(page.getByRole("heading", { level: 1, name: "Start your first bot" })).toBeVisible()
        await expect(page.locator(".version-label")).toHaveText("Canary · Unreleased")
        const notice = page.getByRole("complementary", { name: "Important preview notice" })
        await expect(notice.locator("strong")).toHaveText("IMPORTANT")
        await expect(notice.locator("span")).not.toBeEmpty()
        const titleBox = await page.locator("h1").boundingBox()
        const noticeBox = await notice.boundingBox()
        const descriptionBox = await page.locator(".description").boundingBox()
        expect(noticeBox!.y).toBeGreaterThanOrEqual(titleBox!.y + titleBox!.height)
        expect(descriptionBox!.y).toBeGreaterThanOrEqual(noticeBox!.y + noticeBox!.height)
        await expect(page.locator("html")).toHaveClass("dark")
        expect(
            await page.locator(".docs-content").evaluate((node) => parseFloat(getComputedStyle(node).fontSize)),
        ).toBeGreaterThanOrEqual(20)
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
        if (width === 390) {
            const codeBlocks = page.locator(".docs-content pre:visible")
            expect(await codeBlocks.count()).toBeGreaterThan(2)
            expect(await codeBlocks.evaluateAll((nodes) => nodes.every((node) => node.scrollWidth <= node.clientWidth))).toBe(true)
        }
        await page.screenshot({ path: info.outputPath(`guide-${width}.png`), fullPage: true, animations: "disabled" })
        if (width === 390)
            await page.screenshot({ path: info.outputPath("mobile-reading.png"), animations: "disabled" })
        const accessibility = await new AxeBuilder({ page })
            .withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"])
            .analyze()
        expect(accessibility.violations).toEqual([])
        await page.goto("/docs/dev/api/interfaces/js-ts.Client/#messages")
        await expect(page.getByRole("heading", { level: 1, name: "Client" })).toBeVisible()
        expect(await page.locator("#messages").count()).toBe(1)
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
        await page.screenshot({ path: info.outputPath(`reference-${width}.png`), fullPage: false })
        await page.goto("/docs/dev/api/modules/js-ts/")
        await expect(page.getByRole("heading", { level: 1, name: "JavaScript & TypeScript", exact: true })).toBeVisible()
        const usage = page.locator("details").filter({ has: page.locator("summary", { hasText: "Usage details" }) })
        await expect(usage).not.toHaveAttribute("open")
        if (width >= 1440) await expect(page.getByRole("link", { name: "Usage details", exact: true })).toBeVisible()
        expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
        await page.screenshot({ path: info.outputPath(`api-overview-${width}.png`), fullPage: true, animations: "disabled" })
        await page.goto("/docs/dev/api/")
        await expect(page.locator(".docs-content").getByRole("link", { name: "first-bot guide" })).toBeVisible()
        await expect(page.locator(".docs-content").getByRole("heading", { name: "JavaScript & TypeScript", exact: true })).toBeVisible()
        await expect(page.locator(".docs-content").getByRole("link", { name: "js-ts", exact: true })).toHaveCount(0)
        await expect(page.getByRole("link", { name: /AssetUrlError.*Next Page/ })).toHaveCount(0)
        await page.screenshot({ path: info.outputPath(`api-entry-${width}.png`), fullPage: true, animations: "disabled" })
        expect(errors).toEqual([])
    })
}

test("Search opens by keyboard, finds the current API and returns focus", async ({ page }, info) => {
    await page.goto("/docs/dev/")
    const trigger = page.getByRole("button", { name: "Search Ctrl K", exact: true })
    // Wait for the client-rendered shortcut hint, not only Astro's hydration marker
    await expect(trigger).toBeVisible()
    await page.keyboard.press("Control+k")
    const input = page.getByRole("textbox", { name: "Search Canary documentation" })
    await expect(input).toBeVisible()
    await input.fill("createClient")
    await expect(
        page.getByRole("dialog").getByRole("button", { name: "createClient", exact: true }).first(),
    ).toBeVisible()
    const excerpt = page.locator(".search-excerpt > .min-w-0").first()
    await expect(excerpt).toBeVisible()
    expect(
        await excerpt.evaluate((node) => node.clientHeight / parseFloat(getComputedStyle(node).lineHeight)),
    ).toBeLessThanOrEqual(3.1)
    await page.screenshot({ path: info.outputPath("search.png") })
    await page.keyboard.press("Enter")
    await expect(page).toHaveURL(/\/docs\/dev\/api\/functions\/\w+\.createClient\/?$/)
    await page.goBack()
    await expect(page.locator('astro-island[component-export="Docs"]')).not.toHaveAttribute("ssr")
    await trigger.click()
    await expect(input).toBeVisible()
    await page.keyboard.press("Escape")
    await expect(input).not.toBeVisible()
    await expect(trigger).toBeFocused()
    await page.locator(".docs-content").getByRole("link", { name: "Start your first bot", exact: true }).click()
    await expect(page).toHaveURL(/\/docs\/dev\/quick-start\/?$/)
    await page.goBack()
    await expect(page.getByRole("heading", { name: "Build a Fluxer bot", exact: true })).toBeVisible()
})

test("Dark reading remains usable with enlarged text and reduced motion", async ({ page }) => {
    await page.emulateMedia({ reducedMotion: "reduce" })
    await page.setViewportSize({ width: 780, height: 900 })
    await page.goto("/docs/dev/quick-start/")
    await page.addStyleTag({ content: ":root { font-size: 36px !important; }" })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await expect(page.getByRole("heading", { level: 1 })).toBeVisible()
})

test("API navigation stays compact on a deep symbol without losing reference access", async ({ page }) => {
    await page.setViewportSize({ width: 1440, height: 900 })
    await page.goto("/docs/dev/api/interfaces/js-ts.Client/#messages")
    await expect(page.locator('astro-island[component-export="Docs"]')).not.toHaveAttribute("ssr")
    const sidebar = page.locator("#nd-sidebar")
    await expect(sidebar.getByRole("link", { name: "API reference", exact: true })).toBeVisible()
    await expect(sidebar.getByRole("link", { name: "JavaScript & TypeScript", exact: true })).toBeVisible()
    await expect(sidebar.getByRole("link", { name: "Effect-native", exact: true })).toBeVisible()
    expect(await sidebar.getByRole("link").count()).toBeLessThanOrEqual(7)
    await expect(sidebar.getByRole("button", { name: "Interfaces", exact: true })).toHaveCount(0)
    await sidebar.getByRole("link", { name: "JavaScript & TypeScript", exact: true }).click()
    await expect(page.getByRole("heading", { level: 1, name: "JavaScript & TypeScript", exact: true })).toBeVisible()
    await page.locator(".docs-content summary").getByText("Interfaces", { exact: true }).click()
    await expect(page.locator(".docs-content").getByRole("link", { name: "Client", exact: true }).first()).toBeVisible()
    await page.goto("/docs/dev/api/modules/js-ts/#classes")
    await expect(page.locator(".docs-content").getByRole("link", { name: "AssetUrlError", exact: true })).toBeVisible()
})

test("Inline command choices synchronize, survive navigation and reload, and copy the displayed command", async ({ page, context }) => {
    await context.grantPermissions(["clipboard-read", "clipboard-write"])
    const errors: string[] = []
    page.on("pageerror", (error) => errors.push(error.message))
    await page.goto("/docs/dev/quick-start/")
    const blocks = page.locator("[data-command-block]")
    await expect(blocks).toHaveCount(4)
    const manager = blocks.first().getByLabel("Package manager", { exact: true })
    await expect(manager).toBeEnabled()
    await expect(manager).toHaveValue("npm")
    await manager.selectOption("pnpm")
    await expect(blocks.first().locator("[data-command-code]")).toHaveText("pnpm add --save-exact @neontechspace/fluxerly@VERSION")
    for (const block of await blocks.all()) {
        await expect(block.getByLabel("Package manager", { exact: true })).toHaveValue("pnpm")
    }
    await blocks.first().getByRole("button", { name: "Copy", exact: true }).click()
    await expect(blocks.first().getByRole("status")).toHaveText("Copied")
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe("pnpm add --save-exact @neontechspace/fluxerly@VERSION")
    await page.getByText("Using TypeScript or Effect?", { exact: true }).click()
    await blocks.last().getByLabel("Package manager", { exact: true }).selectOption("npm")
    await expect(blocks.first().locator("[data-command-code]")).toHaveText("npm install --save-exact @neontechspace/fluxerly@VERSION")
    await expect(blocks.last().locator("[data-command-code]")).toHaveText("npm list effect")
    await expect(blocks.nth(1).locator("[data-command-code]")).toHaveText("node bot.js")
    await blocks.nth(1).getByLabel("Package manager", { exact: true }).selectOption("pnpm")
    await page.locator(".docs-content").getByRole("link", { name: /client.s message methods/ }).click()
    await expect(page.getByRole("heading", { level: 1, name: "Client", exact: true })).toBeVisible()
    await page.goBack()
    await expect(blocks.first().getByLabel("Package manager", { exact: true })).toHaveValue("pnpm")
    await page.reload()
    await expect(blocks.first().getByLabel("Package manager", { exact: true })).toHaveValue("pnpm")
    await page.getByText("Using TypeScript or Effect?", { exact: true }).click()
    const accessibility = await new AxeBuilder({ page }).withTags(["wcag2a", "wcag2aa", "wcag21aa", "wcag22aa"]).analyze()
    expect(accessibility.violations).toEqual([])
    expect(errors).toEqual([])
})

test("Package manager selector remains keyboard usable on mobile and keeps working without storage", async ({ page }) => {
    await page.setViewportSize({ width: 390, height: 900 })
    await page.addInitScript(() => {
        Object.defineProperty(window, "localStorage", { get() { throw new DOMException("Storage blocked", "SecurityError") } })
    })
    const errors: string[] = []
    page.on("pageerror", (error) => errors.push(error.message))
    await page.goto("/docs/dev/quick-start/")
    const first = page.locator("[data-command-block]").first()
    const manager = first.getByLabel("Package manager", { exact: true })
    await expect(manager).toBeEnabled()
    await manager.focus()
    await page.keyboard.press("p")
    await page.keyboard.press("Escape")
    await expect(manager).toHaveValue("pnpm")
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.locator(".docs-content").getByRole("link", { name: /client.s message methods/ }).click()
    await expect(page.getByRole("heading", { level: 1, name: "Client", exact: true })).toBeVisible()
    await page.goBack()
    await expect(first.getByLabel("Package manager", { exact: true })).toHaveValue("pnpm")
    expect(errors).toEqual([])
})

test("Default commands remain readable without JavaScript", async ({ browser }) => {
    const context = await browser.newContext({ javaScriptEnabled: false })
    try {
        const page = await context.newPage()
        await page.goto("/docs/dev/quick-start/")
        const first = page.locator("[data-command-block]").first()
        await expect(first.locator("[data-command-code]")).toHaveText("npm install --save-exact @neontechspace/fluxerly@VERSION")
        await expect(first.getByLabel("Package manager", { exact: true })).toBeDisabled()
        await expect(first.getByText("Enable JavaScript to change command preferences")).toBeVisible()
    } finally { await context.close() }
})
