import { test, expect } from "@playwright/test"

const preferenceKey = "fluxerly.docs.example-language"

test("Example language follows guide filenames, execution, navigation, reload and copy", async ({ page, context }) => {
    await context.grantPermissions(["clipboard-read", "clipboard-write"])
    await page.goto("/docs/dev/quick-start/")
    const example = page.locator("[data-example-block]").first()
    const selector = example.getByRole("combobox", { name: "Example language" })
    await expect(selector).toBeEnabled()
    await expect(selector).toHaveValue("js")
    await selector.selectOption("ts")
    await expect(page.locator("[data-example-filename]")).toHaveText("bot.ts")
    await expect(page.locator("[data-command-code]").filter({ hasText: "node bot.ts" })).toHaveCount(1)
    await expect(example.locator('[data-example-variant="js"]')).toBeHidden()
    await expect(example.locator('[data-example-variant="ts"]')).toBeVisible()
    const code = await example.locator('[data-example-variant="ts"] code').textContent()
    await example.getByRole("button", { name: "Copy", exact: true }).click()
    await expect(example.locator("[data-example-copy-status]")).toHaveText("Copied")
    const clipboard = await page.evaluate(() => navigator.clipboard.readText())
    expect(clipboard.replaceAll("\r\n", "\n")).toBe(code?.replaceAll("\r\n", "\n"))
    expect(await page.evaluate((key) => localStorage.getItem(key), preferenceKey)).toBe("ts")
    await page.reload()
    await expect(selector).toHaveValue("ts")
    await expect(page.locator("[data-example-filename]")).toHaveText("bot.ts")

    await page.locator(".docs-content").getByRole("link", { name: /client.s message methods/ }).click()
    await expect(page.locator("h1")).toHaveText("Client")
    const selectors = page.locator("[data-example-language]")
    expect(await selectors.count()).toBeGreaterThan(1)
    for (const select of await selectors.all()) await expect(select).toHaveValue("ts")
    await selectors.first().selectOption("js")
    for (const select of await selectors.all()) await expect(select).toHaveValue("js")
    await page.goBack()
    await expect(selector).toHaveValue("js")
    await expect(page.locator("[data-example-filename]")).toHaveText("bot.js")
    await expect(page.locator("[data-command-code]").filter({ hasText: "node bot.js" })).toHaveCount(1)
})

test("Messages guide defaults to JavaScript and copies each selected language faithfully", async ({ page, context }) => {
    await context.grantPermissions(["clipboard-read", "clipboard-write"])
    await page.goto("/docs/dev/messages/")
    const examples = page.locator(".docs-content [data-example-block]")
    const first = examples.first()
    await expect(first).toBeVisible()
    expect(await examples.count()).toBeGreaterThan(1)
    const selector = first.getByRole("combobox", { name: "Example language" })
    await expect(selector).toHaveValue("js")
    const javascript = await first.locator('[data-example-variant="js"] code').textContent()
    await first.getByRole("button", { name: "Copy", exact: true }).click()
    await expect(first.locator("[data-example-copy-status]")).toHaveText("Copied")
    expect((await page.evaluate(() => navigator.clipboard.readText())).replaceAll("\r\n", "\n"))
        .toBe(javascript?.replaceAll("\r\n", "\n"))

    await selector.selectOption("ts")
    for (const example of await examples.all()) {
        await expect(example.getByRole("combobox", { name: "Example language" })).toHaveValue("ts")
        await expect(example.locator('[data-example-variant="js"]')).toBeHidden()
        await expect(example.locator('[data-example-variant="ts"]')).toBeVisible()
    }
    const typescript = await first.locator('[data-example-variant="ts"] code').textContent()
    await first.getByRole("button", { name: "Copy", exact: true }).click()
    await expect(first.locator("[data-example-copy-status]")).toHaveText("Copied")
    expect((await page.evaluate(() => navigator.clipboard.readText())).replaceAll("\r\n", "\n"))
        .toBe(typescript?.replaceAll("\r\n", "\n"))
})

test("Canonical API TypeScript retains types that the executable JavaScript variant removes", async ({ page }) => {
    await page.goto("/docs/dev/api/variables/js-ts.text/")
    const example = page.locator("[data-example-block]").first()
    await expect(example.locator('[data-example-variant="js"]')).toBeVisible()
    const javascript = await example.locator('[data-example-variant="js"] code').textContent()
    expect(javascript).toContain("pureHelpersExample(bits, content)")
    expect(javascript).not.toContain("bits: bigint")
    expect(javascript).toContain('from "@neontechspace/fluxerly"')
    const selector = example.getByRole("combobox", { name: "Example language" })
    await selector.focus()
    await selector.press("ArrowDown")
    await selector.press("Enter")
    await expect(selector).toHaveValue("ts")
    await expect(example.locator('[data-example-variant="ts"]')).toBeVisible()
    await expect(example.locator('[data-example-variant="ts"] code')).toContainText("bits: bigint, content: string")
})

test("Global JavaScript preference never changes the native Effect guide examples", async ({ page }) => {
    await page.addInitScript((key) => localStorage.setItem(key, "js"), preferenceKey)
    await page.goto("/docs/dev/api/modules/Effect/")
    await expect(page.locator("[data-example-language]")).toHaveCount(0)
    await expect(page.locator(".docs-content pre").first()).toBeVisible()
    await expect(page.locator(".docs-content pre").first()).toContainText("Effect")
    for (const slug of ["effect-first-bot", "effect-workflows"]) {
        await page.goto(`/docs/dev/${slug}/`)
        await expect(page.getByRole("heading", { level: 1 })).toBeVisible()
        await expect(page.locator("[data-example-language]")).toHaveCount(0)
        await expect(page.locator("[data-example-block]")).toHaveCount(0)
        await expect(page.locator(".docs-content pre:visible").first()).toBeVisible()
    }
})

test("Example preferences synchronize between open pages", async ({ page, context }) => {
    await page.goto("/docs/dev/quick-start/")
    const other = await context.newPage()
    await other.goto("/docs/dev/quick-start/")
    await page.locator("[data-example-language]").first().selectOption("ts")
    await expect(other.locator("[data-example-language]").first()).toHaveValue("ts")
    await expect(other.locator("[data-example-filename]")).toHaveText("bot.ts")
    await expect(other.locator("[data-command-code]").filter({ hasText: "node bot.ts" })).toHaveCount(1)
    await other.close()
})

test("Blocked storage leaves language selection and execution usable for the current navigation", async ({ page }) => {
    await page.addInitScript(() => {
        Object.defineProperty(window, "localStorage", { get() { throw new DOMException("Blocked", "SecurityError") } })
    })
    await page.goto("/docs/dev/quick-start/")
    await page.locator("[data-example-language]").first().selectOption("ts")
    await expect(page.locator("[data-example-filename]")).toHaveText("bot.ts")
    await expect(page.locator("[data-command-code]").filter({ hasText: "node bot.ts" })).toHaveCount(1)
    await page.locator(".docs-content").getByRole("link", { name: /client.s message methods/ }).click()
    await expect(page.locator("[data-example-language]").first()).toHaveValue("ts")
})

test("Without client JavaScript, the first bot remains readable and runnable", async ({ browser }) => {
    const context = await browser.newContext({ javaScriptEnabled: false })
    const page = await context.newPage()
    await page.goto("http://127.0.0.1:4322/docs/dev/quick-start/")
    const example = page.locator("[data-example-block]").first()
    await expect(example.getByRole("combobox", { name: "Example language" })).toBeDisabled()
    await expect(example.locator('[data-example-variant="js"]')).toBeVisible()
    await expect(example.locator('[data-example-variant="ts"]')).toBeHidden()
    await expect(example.locator("[data-example-fallback]")).toBeVisible()
    await expect(example.getByRole("button", { name: "Copy" })).toHaveCount(0)
    await expect(page.locator("[data-example-filename]")).toHaveText("bot.js")
    await expect(page.locator("[data-command-code]").filter({ hasText: "node bot.js" })).toHaveCount(1)
    await context.close()
})
